import { t, type DeclarationContent } from "intlayer";

const preferencesPageContent = {
  key: "preferences-page",
  content: {
    metadata: {
      title: t({
        en: "Preferences - Lianki",
        zh: "偏好设置 - Lianki",
        ja: "設定 - Lianki",
        ko: "환경설정 - Lianki",
        hi: "प्राथमिकताएँ - Lianki",
        es: "Preferencias - Lianki",
        fr: "Préférences - Lianki",
        ar: "التفضيلات - Lianki",
        bn: "পছন্দসমূহ - Lianki",
        pt: "Preferências - Lianki",
        ru: "Настройки - Lianki",
        ur: "ترجیحات - Lianki",
        id: "Preferensi - Lianki",
        de: "Einstellungen - Lianki",
        sw: "Mapendeleo - Lianki",
        mr: "प्राधान्ये - Lianki",
      }),
      description: t({
        en: "Configure your Lianki preferences and settings",
        zh: "配置您的 Lianki 偏好设置",
        ja: "Lianki の設定を構成",
        ko: "Lianki 환경설정 구성",
        hi: "अपनी Lianki प्राथमिकताएँ और सेटिंग्स कॉन्फ़िगर करें",
        es: "Configure sus preferencias y ajustes de Lianki",
        fr: "Configurez vos préférences et paramètres Lianki",
        ar: "قم بتكوين تفضيلات وإعدادات Lianki الخاصة بك",
        bn: "আপনার Lianki পছন্দসমূহ এবং সেটিংস কনফিগার করুন",
        pt: "Configure suas preferências e configurações do Lianki",
        ru: "Настройте ваши предпочтения и параметры Lianki",
        ur: "اپنی Lianki ترجیحات اور سیٹنگز کو ترتیب دیں",
        id: "Konfigurasi preferensi dan pengaturan Lianki Anda",
        de: "Konfigurieren Sie Ihre Lianki-Einstellungen und -Präferenzen",
        sw: "Sanidi mapendeleo na mipangilio yako ya Lianki",
        mr: "तुमची Lianki प्राधान्ये आणि सेटिंग्ज कॉन्फिगर करा",
      }),
    },
    loading: t({
      en: "Loading preferences...",
      zh: "加载偏好设置中...",
      ja: "設定を読み込み中...",
      ko: "환경설정 로드 중...",
      hi: "प्राथमिकताएँ लोड हो रही हैं...",
      es: "Cargando preferencias...",
      fr: "Chargement des préférences...",
      ar: "جاري تحميل التفضيلات...",
      bn: "পছন্দসমূহ লোড হচ্ছে...",
      pt: "Carregando preferências...",
      ru: "Загрузка настроек...",
      ur: "ترجیحات لوڈ ہو رہی ہیں...",
      id: "Memuat preferensi...",
      de: "Einstellungen werden geladen...",
      sw: "Inapakia mapendeleo...",
      mr: "प्राधान्ये लोड होत आहेत...",
    }),
    heading: t({
      en: "Preferences",
      zh: "偏好设置",
      ja: "設定",
      ko: "환경설정",
      hi: "प्राथमिकताएँ",
      es: "Preferencias",
      fr: "Préférences",
      ar: "التفضيلات",
      bn: "পছন্দসমূহ",
      pt: "Preferências",
      ru: "Настройки",
      ur: "ترجیحات",
      id: "Preferensi",
      de: "Einstellungen",
      sw: "Mapendeleo",
      mr: "प्राधान्ये",
    }),
    mobileFilters: {
      heading: t({
        en: "Mobile Review Filters",
        zh: "移动端复习过滤器",
        ja: "モバイルレビューフィルター",
        ko: "모바일 복습 필터",
        hi: "मोबाइल समीक्षा फ़िल्टर",
        es: "Filtros de Revisión Móvil",
        fr: "Filtres de Révision Mobile",
        ar: "مرشحات المراجعة على الهاتف المحمول",
        bn: "মোবাইল পর্যালোচনা ফিল্টার",
        pt: "Filtros de Revisão Móvel",
        ru: "Фильтры Мобильного Обзора",
        ur: "موبائل جائزہ فلٹرز",
        id: "Filter Tinjauan Seluler",
        de: "Mobile Überprüfungsfilter",
        sw: "Vichujio vya Mapitio ya Simu",
        mr: "मोबाइल पुनरावलोकन फिल्टर",
      }),
      description: t({
        en: "Filter cards from your mobile review queue by domain, title, or URL pattern. Useful for preventing app hijacking or excluding certain types of content on mobile.",
        zh: "按域名、标题或 URL 模式过滤移动端复习队列中的卡片。用于防止应用劫持或在移动设备上排除某些类型的内容。",
        ja: "ドメイン、タイトル、または URL パターンでモバイルレビューキューからカードをフィルタリングします。アプリのハイジャックを防止したり、モバイルで特定の種類のコンテンツを除外するのに役立ちます。",
        ko: "도메인, 제목 또는 URL 패턴으로 모바일 복습 대기열에서 카드를 필터링합니다. 앱 하이재킹을 방지하거나 모바일에서 특정 유형의 콘텐츠를 제외하는 데 유용합니다.",
        hi: "अपनी मोबाइल समीक्षा कतार से डोमेन, शीर्षक या URL पैटर्न द्वारा कार्ड फ़िल्टर करें। ऐप हाईजैकिंग को रोकने या मोबाइल पर कुछ प्रकार की सामग्री को बाहर करने के लिए उपयोगी।",
        es: "Filtra tarjetas de tu cola de revisión móvil por dominio, título o patrón de URL. Útil para prevenir secuestro de aplicaciones o excluir ciertos tipos de contenido en móvil.",
        fr: "Filtrez les cartes de votre file de révision mobile par domaine, titre ou modèle d'URL. Utile pour prévenir le détournement d'applications ou exclure certains types de contenu sur mobile.",
        ar: "قم بتصفية البطاقات من قائمة المراجعة على الهاتف المحمول حسب النطاق أو العنوان أو نمط URL. مفيد لمنع اختطاف التطبيقات أو استبعاد أنواع معينة من المحتوى على الهاتف المحمول.",
        bn: "ডোমেন, শিরোনাম বা URL প্যাটার্ন দ্বারা আপনার মোবাইল পর্যালোচনা সারি থেকে কার্ড ফিল্টার করুন। অ্যাপ হাইজ্যাকিং প্রতিরোধ বা মোবাইলে নির্দিষ্ট ধরনের সামগ্রী বাদ দেওয়ার জন্য উপযোগী।",
        pt: "Filtre cartões da sua fila de revisão móvel por domínio, título ou padrão de URL. Útil para prevenir sequestro de aplicativos ou excluir certos tipos de conteúdo no celular.",
        ru: "Фильтруйте карточки из вашей очереди мобильного просмотра по домену, заголовку или шаблону URL. Полезно для предотвращения перехвата приложений или исключения определенных типов контента на мобильных устройствах.",
        ur: "اپنی موبائل جائزہ قطار سے ڈومین، عنوان، یا URL پیٹرن کے ذریعے کارڈز فلٹر کریں۔ ایپ ہائی جیکنگ کو روکنے یا موبائل پر مخصوص قسم کے مواد کو خارج کرنے کے لیے مفید۔",
        id: "Filter kartu dari antrean tinjauan seluler Anda berdasarkan domain, judul, atau pola URL. Berguna untuk mencegah pembajakan aplikasi atau mengecualikan jenis konten tertentu di seluler.",
        de: "Filtern Sie Karten aus Ihrer mobilen Überprüfungswarteschlange nach Domain, Titel oder URL-Muster. Nützlich zur Verhinderung von App-Hijacking oder zum Ausschluss bestimmter Inhaltstypen auf Mobilgeräten.",
        sw: "Chuja kadi kutoka foleni yako ya mapitio ya simu kwa kikoa, kichwa, au muundo wa URL. Inafaa kuzuia utekaji wa programu au kuondoa aina fulani za maudhui kwenye simu.",
        mr: "तुमच्या मोबाइल पुनरावलोकन रांगेतून डोमेन, शीर्षक किंवा URL पॅटर्नद्वारे कार्ड फिल्टर करा. अॅप हायजॅकिंग टाळण्यासाठी किंवा मोबाइलवर विशिष्ट प्रकारच्या सामग्रीला वगळण्यासाठी उपयुक्त.",
      }),
      activeFilters: t({
        en: "Active Filters",
        zh: "活动过滤器",
        ja: "アクティブフィルター",
        ko: "활성 필터",
        hi: "सक्रिय फ़िल्टर",
        es: "Filtros Activos",
        fr: "Filtres Actifs",
        ar: "المرشحات النشطة",
        bn: "সক্রিয় ফিল্টার",
        pt: "Filtros Ativos",
        ru: "Активные Фильтры",
        ur: "فعال فلٹرز",
        id: "Filter Aktif",
        de: "Aktive Filter",
        sw: "Vichujio Hai",
        mr: "सक्रिय फिल्टर",
      }),
      noFilters: t({
        en: "No filters configured",
        zh: "未配置过滤器",
        ja: "フィルターが設定されていません",
        ko: "구성된 필터 없음",
        hi: "कोई फ़िल्टर कॉन्फ़िगर नहीं किया गया",
        es: "No hay filtros configurados",
        fr: "Aucun filtre configuré",
        ar: "لا توجد مرشحات تم تكوينها",
        bn: "কোনও ফিল্টার কনফিগার করা হয়নি",
        pt: "Nenhum filtro configurado",
        ru: "Фильтры не настроены",
        ur: "کوئی فلٹر ترتیب نہیں دیا گیا",
        id: "Tidak ada filter yang dikonfigurasi",
        de: "Keine Filter konfiguriert",
        sw: "Hakuna vichujio vilivyosanidiwa",
        mr: "कोणतेही फिल्टर कॉन्फिगर केलेले नाहीत",
      }),
      remove: t({
        en: "Remove",
        zh: "移除",
        ja: "削除",
        ko: "제거",
        hi: "हटाएँ",
        es: "Eliminar",
        fr: "Supprimer",
        ar: "إزالة",
        bn: "সরান",
        pt: "Remover",
        ru: "Удалить",
        ur: "ہٹائیں",
        id: "Hapus",
        de: "Entfernen",
        sw: "Ondoa",
        mr: "काढा",
      }),
      addPattern: t({
        en: "Add Filter Pattern",
        zh: "添加过滤器模式",
        ja: "フィルターパターンを追加",
        ko: "필터 패턴 추가",
        hi: "फ़िल्टर पैटर्न जोड़ें",
        es: "Agregar Patrón de Filtro",
        fr: "Ajouter un Modèle de Filtre",
        ar: "إضافة نمط تصفية",
        bn: "ফিল্টার প্যাটার্ন যোগ করুন",
        pt: "Adicionar Padrão de Filtro",
        ru: "Добавить Шаблон Фильтра",
        ur: "فلٹر پیٹرن شامل کریں",
        id: "Tambah Pola Filter",
        de: "Filtermuster Hinzufügen",
        sw: "Ongeza Muundo wa Kichujio",
        mr: "फिल्टर पॅटर्न जोडा",
      }),
      filterType: t({
        en: "Filter Type",
        zh: "过滤器类型",
        ja: "フィルタータイプ",
        ko: "필터 유형",
        hi: "फ़िल्टर प्रकार",
        es: "Tipo de Filtro",
        fr: "Type de Filtre",
        ar: "نوع التصفية",
        bn: "ফিল্টার প্রকার",
        pt: "Tipo de Filtro",
        ru: "Тип Фильтра",
        ur: "فلٹر کی قسم",
        id: "Jenis Filter",
        de: "Filtertyp",
        sw: "Aina ya Kichujio",
        mr: "फिल्टर प्रकार",
      }),
      domain: t({
        en: "Domain",
        zh: "域名",
        ja: "ドメイン",
        ko: "도메인",
        hi: "डोमेन",
        es: "Dominio",
        fr: "Domaine",
        ar: "النطاق",
        bn: "ডোমেন",
        pt: "Domínio",
        ru: "Домен",
        ur: "ڈومین",
        id: "Domain",
        de: "Domain",
        sw: "Kikoa",
        mr: "डोमेन",
      }),
      title: t({
        en: "Title",
        zh: "标题",
        ja: "タイトル",
        ko: "제목",
        hi: "शीर्षक",
        es: "Título",
        fr: "Titre",
        ar: "العنوان",
        bn: "শিরোনাম",
        pt: "Título",
        ru: "Заголовок",
        ur: "عنوان",
        id: "Judul",
        de: "Titel",
        sw: "Kichwa",
        mr: "शीर्षक",
      }),
      url: t({
        en: "URL",
        zh: "URL",
        ja: "URL",
        ko: "URL",
        hi: "URL",
        es: "URL",
        fr: "URL",
        ar: "URL",
        bn: "URL",
        pt: "URL",
        ru: "URL",
        ur: "URL",
        id: "URL",
        de: "URL",
        sw: "URL",
        mr: "URL",
      }),
      patternLabel: t({
        en: "Pattern",
        zh: "模式",
        ja: "パターン",
        ko: "패턴",
        hi: "पैटर्न",
        es: "Patrón",
        fr: "Modèle",
        ar: "النمط",
        bn: "প্যাটার্ন",
        pt: "Padrão",
        ru: "Шаблон",
        ur: "پیٹرن",
        id: "Pola",
        de: "Muster",
        sw: "Muundo",
        mr: "पॅटर्न",
      }),
      patternPlaceholder: t({
        en: "Enter {type} pattern...",
        zh: "输入 {type} 模式...",
        ja: "{type} パターンを入力...",
        ko: "{type} 패턴 입력...",
        hi: "{type} पैटर्न दर्ज करें...",
        es: "Ingrese patrón de {type}...",
        fr: "Entrez le modèle {type}...",
        ar: "أدخل نمط {type}...",
        bn: "{type} প্যাটার্ন লিখুন...",
        pt: "Insira o padrão {type}...",
        ru: "Введите шаблон {type}...",
        ur: "{type} پیٹرن درج کریں...",
        id: "Masukkan pola {type}...",
        de: "Geben Sie {type}-Muster ein...",
        sw: "Ingiza muundo wa {type}...",
        mr: "{type} पॅटर्न प्रविष्ट करा...",
      }),
      useRegex: t({
        en: "Use Regular Expression (regex)",
        zh: "使用正则表达式 (regex)",
        ja: "正規表現を使用 (regex)",
        ko: "정규 표현식 사용 (regex)",
        hi: "नियमित अभिव्यक्ति का उपयोग करें (regex)",
        es: "Usar Expresión Regular (regex)",
        fr: "Utiliser une Expression Régulière (regex)",
        ar: "استخدام التعبير العادي (regex)",
        bn: "রেগুলার এক্সপ্রেশন ব্যবহার করুন (regex)",
        pt: "Usar Expressão Regular (regex)",
        ru: "Использовать Регулярное Выражение (regex)",
        ur: "ریگولر ایکسپریشن استعمال کریں (regex)",
        id: "Gunakan Ekspresi Reguler (regex)",
        de: "Regulären Ausdruck Verwenden (regex)",
        sw: "Tumia Usemi wa Kawaida (regex)",
        mr: "नियमित अभिव्यक्ती वापरा (regex)",
      }),
      regexHelp: t({
        en: "Enable this to use regex patterns for advanced matching",
        zh: "启用此选项可使用正则表达式进行高级匹配",
        ja: "高度なマッチングのために正規表現パターンを使用する場合は、これを有効にします",
        ko: "고급 매칭을 위해 정규 표현식 패턴을 사용하려면 이 옵션을 활성화하세요",
        hi: "उन्नत मिलान के लिए regex पैटर्न का उपयोग करने के लिए इसे सक्षम करें",
        es: "Habilite esto para usar patrones regex para coincidencias avanzadas",
        fr: "Activez ceci pour utiliser des modèles regex pour une correspondance avancée",
        ar: "قم بتمكين هذا لاستخدام أنماط regex للمطابقة المتقدمة",
        bn: "উন্নত মিলের জন্য regex প্যাটার্ন ব্যবহার করতে এটি সক্ষম করুন",
        pt: "Habilite isso para usar padrões regex para correspondência avançada",
        ru: "Включите это, чтобы использовать шаблоны regex для расширенного сопоставления",
        ur: "پیچیدہ میچنگ کے لیے regex پیٹرن استعمال کرنے کے لیے اسے فعال کریں",
        id: "Aktifkan ini untuk menggunakan pola regex untuk pencocokan lanjutan",
        de: "Aktivieren Sie dies, um Regex-Muster für erweitertes Matching zu verwenden",
        sw: "Wezesha hii kutumia mifumo ya regex kwa ulinganishaji wa hali ya juu",
        mr: "प्रगत जुळणीसाठी regex पॅटर्न वापरण्यासाठी हे सक्षम करा",
      }),
      addFilter: t({
        en: "Add Filter",
        zh: "添加过滤器",
        ja: "フィルターを追加",
        ko: "필터 추가",
        hi: "फ़िल्टर जोड़ें",
        es: "Agregar Filtro",
        fr: "Ajouter un Filtre",
        ar: "إضافة مرشح",
        bn: "ফিল্টার যোগ করুন",
        pt: "Adicionar Filtro",
        ru: "Добавить Фильтр",
        ur: "فلٹر شامل کریں",
        id: "Tambah Filter",
        de: "Filter Hinzufügen",
        sw: "Ongeza Kichujio",
        mr: "फिल्टर जोडा",
      }),
      howItWorks: t({
        en: "How Filtering Works",
        zh: "过滤工作原理",
        ja: "フィルタリングの仕組み",
        ko: "필터링 작동 방식",
        hi: "फ़िल्टरिंग कैसे काम करती है",
        es: "Cómo Funciona el Filtrado",
        fr: "Comment Fonctionne le Filtrage",
        ar: "كيف يعمل التصفية",
        bn: "ফিল্টারিং কীভাবে কাজ করে",
        pt: "Como Funciona a Filtragem",
        ru: "Как Работает Фильтрация",
        ur: "فلٹرنگ کیسے کام کرتی ہے",
        id: "Cara Kerja Penyaringan",
        de: "Wie Filterung Funktioniert",
        sw: "Jinsi Kuchuja Inavyofanya Kazi",
        mr: "फिल्टरिंग कसे कार्य करते",
      }),
      helpDomain: t({
        en: 'Domain: Matches the hostname (e.g., "zhihu.com" blocks all Zhihu pages)',
        zh: '域名：匹配主机名（例如，"zhihu.com" 阻止所有知乎页面）',
        ja: "ドメイン：ホスト名に一致（例：「zhihu.com」はすべての知乎ページをブロック）",
        ko: '도메인: 호스트 이름과 일치 (예: "zhihu.com"은 모든 지후 페이지를 차단)',
        hi: 'डोमेन: होस्टनेम से मेल खाता है (उदा., "zhihu.com" सभी Zhihu पृष्ठों को ब्लॉक करता है)',
        es: 'Dominio: Coincide con el nombre de host (ej., "zhihu.com" bloquea todas las páginas de Zhihu)',
        fr: 'Domaine : Correspond au nom d\'hôte (par ex., "zhihu.com" bloque toutes les pages Zhihu)',
        ar: 'النطاق: يطابق اسم المضيف (على سبيل المثال، "zhihu.com" يحظر جميع صفحات Zhihu)',
        bn: 'ডোমেন: হোস্টনাম মেলে (যেমন, "zhihu.com" সমস্ত Zhihu পৃষ্ঠা ব্লক করে)',
        pt: 'Domínio: Corresponde ao nome do host (ex., "zhihu.com" bloqueia todas as páginas do Zhihu)',
        ru: 'Домен: Соответствует имени хоста (например, "zhihu.com" блокирует все страницы Zhihu)',
        ur: 'ڈومین: میزبان نام سے میل کھاتا ہے (مثلاً، "zhihu.com" تمام Zhihu صفحات کو بلاک کرتا ہے)',
        id: 'Domain: Cocok dengan nama host (mis., "zhihu.com" memblokir semua halaman Zhihu)',
        de: 'Domain: Passt zum Hostnamen (z.B. "zhihu.com" blockiert alle Zhihu-Seiten)',
        sw: 'Kikoa: Inaingiana na jina la mwenyeji (k.m., "zhihu.com" inazuia kurasa zote za Zhihu)',
        mr: 'डोमेन: होस्टनेमशी जुळते (उदा., "zhihu.com" सर्व Zhihu पृष्ठे ब्लॉक करते)',
      }),
      helpTitle: t({
        en: 'Title: Matches card title text (e.g., "draft" blocks cards with "draft" in title)',
        zh: '标题：匹配卡片标题文本（例如，"draft" 阻止标题中包含 "draft" 的卡片）',
        ja: "タイトル：カードタイトルテキストに一致（例：「draft」はタイトルに「draft」を含むカードをブロック）",
        ko: '제목: 카드 제목 텍스트와 일치 (예: "draft"는 제목에 "draft"가 있는 카드를 차단)',
        hi: 'शीर्षक: कार्ड शीर्षक टेक्स्ट से मेल खाता है (उदा., "draft" शीर्षक में "draft" वाले कार्ड को ब्लॉक करता है)',
        es: 'Título: Coincide con el texto del título de la tarjeta (ej., "draft" bloquea tarjetas con "draft" en el título)',
        fr: 'Titre : Correspond au texte du titre de la carte (par ex., "draft" bloque les cartes avec "draft" dans le titre)',
        ar: 'العنوان: يطابق نص عنوان البطاقة (على سبيل المثال، "draft" يحظر البطاقات التي تحتوي على "draft" في العنوان)',
        bn: 'শিরোনাম: কার্ড শিরোনাম টেক্সট মেলে (যেমন, "draft" শিরোনামে "draft" থাকা কার্ড ব্লক করে)',
        pt: 'Título: Corresponde ao texto do título do cartão (ex., "draft" bloqueia cartões com "draft" no título)',
        ru: 'Заголовок: Соответствует тексту заголовка карточки (например, "draft" блокирует карточки с "draft" в заголовке)',
        ur: 'عنوان: کارڈ کے عنوان کے متن سے میل کھاتا ہے (مثلاً، "draft" عنوان میں "draft" والے کارڈز کو بلاک کرتا ہے)',
        id: 'Judul: Cocok dengan teks judul kartu (mis., "draft" memblokir kartu dengan "draft" di judul)',
        de: 'Titel: Passt zum Kartentiteltext (z.B. "draft" blockiert Karten mit "draft" im Titel)',
        sw: 'Kichwa: Inaingiana na maandishi ya kichwa cha kadi (k.m., "draft" inazuia kadi zenye "draft" katika kichwa)',
        mr: 'शीर्षक: कार्ड शीर्षक मजकूराशी जुळते (उदा., "draft" शीर्षकात "draft" असलेले कार्ड ब्लॉक करते)',
      }),
      helpUrl: t({
        en: 'URL: Matches the full URL (e.g., "/admin" blocks all admin pages)',
        zh: 'URL：匹配完整 URL（例如，"/admin" 阻止所有管理页面）',
        ja: "URL：完全な URL に一致（例：「/admin」はすべての管理ページをブロック）",
        ko: 'URL: 전체 URL과 일치 (예: "/admin"은 모든 관리자 페이지를 차단)',
        hi: 'URL: पूर्ण URL से मेल खाता है (उदा., "/admin" सभी व्यवस्थापक पृष्ठों को ब्लॉक करता है)',
        es: 'URL: Coincide con la URL completa (ej., "/admin" bloquea todas las páginas de administración)',
        fr: "URL : Correspond à l'URL complète (par ex., \"/admin\" bloque toutes les pages d'administration)",
        ar: 'URL: يطابق عنوان URL الكامل (على سبيل المثال، "/admin" يحظر جميع صفحات الإدارة)',
        bn: 'URL: সম্পূর্ণ URL মেলে (যেমন, "/admin" সমস্ত প্রশাসক পৃষ্ঠা ব্লক করে)',
        pt: 'URL: Corresponde à URL completa (ex., "/admin" bloqueia todas as páginas de administração)',
        ru: 'URL: Соответствует полному URL (например, "/admin" блокирует все административные страницы)',
        ur: 'URL: مکمل URL سے میل کھاتا ہے (مثلاً، "/admin" تمام ایڈمن صفحات کو بلاک کرتا ہے)',
        id: 'URL: Cocok dengan URL lengkap (mis., "/admin" memblokir semua halaman admin)',
        de: 'URL: Passt zur vollständigen URL (z.B. "/admin" blockiert alle Admin-Seiten)',
        sw: 'URL: Inaingiana na URL kamili (k.m., "/admin" inazuia kurasa zote za msimamizi)',
        mr: 'URL: संपूर्ण URL शी जुळते (उदा., "/admin" सर्व प्रशासक पृष्ठे ब्लॉक करते)',
      }),
      helpRegex: t({
        en: "Regex: Use .* for wildcards, ^ for start, $ for end, | for OR, etc.",
        zh: "正则表达式：使用 .* 表示通配符，^ 表示开始，$ 表示结束，| 表示 OR 等",
        ja: "正規表現：ワイルドカードには .*、開始には ^、終了には $、OR には | などを使用",
        ko: "정규식: 와일드카드에는 .*, 시작에는 ^, 끝에는 $, OR에는 | 등을 사용",
        hi: "Regex: वाइल्डकार्ड के लिए .*, शुरुआत के लिए ^, अंत के लिए $, OR के लिए | आदि का उपयोग करें",
        es: "Regex: Use .* para comodines, ^ para inicio, $ para fin, | para O, etc.",
        fr: "Regex : Utilisez .* pour les jokers, ^ pour le début, $ pour la fin, | pour OU, etc.",
        ar: "Regex: استخدم .* للأحرف البدل، ^ للبداية، $ للنهاية، | لـ OR، إلخ.",
        bn: "Regex: ওয়াইল্ডকার্ডের জন্য .*, শুরুর জন্য ^, শেষের জন্য $, OR এর জন্য | ইত্যাদি ব্যবহার করুন",
        pt: "Regex: Use .* para curingas, ^ para início, $ para fim, | para OU, etc.",
        ru: "Regex: Используйте .* для подстановочных знаков, ^ для начала, $ для конца, | для ИЛИ и т.д.",
        ur: "Regex: وائلڈ کارڈز کے لیے .*، شروعات کے لیے ^، اختتام کے لیے $، OR کے لیے | وغیرہ استعمال کریں",
        id: "Regex: Gunakan .* untuk wildcard, ^ untuk awal, $ untuk akhir, | untuk OR, dll.",
        de: "Regex: Verwenden Sie .* für Platzhalter, ^ für Start, $ für Ende, | für ODER usw.",
        sw: "Regex: Tumia .* kwa wildcards, ^ kwa mwanzo, $ kwa mwisho, | kwa AU, n.k.",
        mr: "Regex: वाइल्डकार्डसाठी .*, प्रारंभासाठी ^, शेवटासाठी $, OR साठी | इ. वापरा",
      }),
      helpDisabled: t({
        en: "Disabled filters are saved but won't be applied (toggle checkbox to enable/disable)",
        zh: "已禁用的过滤器会保存但不会应用（切换复选框以启用/禁用）",
        ja: "無効化されたフィルターは保存されますが適用されません（チェックボックスで有効/無効を切り替え）",
        ko: "비활성화된 필터는 저장되지만 적용되지 않습니다 (확인란을 토글하여 활성화/비활성화)",
        hi: "अक्षम फ़िल्टर सहेजे जाते हैं लेकिन लागू नहीं होंगे (सक्षम/अक्षम करने के लिए चेकबॉक्स टॉगल करें)",
        es: "Los filtros deshabilitados se guardan pero no se aplican (active/desactive la casilla para habilitar/deshabilitar)",
        fr: "Les filtres désactivés sont enregistrés mais ne seront pas appliqués (basculez la case à cocher pour activer/désactiver)",
        ar: "يتم حفظ المرشحات المعطلة لكن لن يتم تطبيقها (قم بتبديل مربع الاختيار للتمكين/التعطيل)",
        bn: "নিষ্ক্রিয় ফিল্টারগুলি সংরক্ষিত হয় কিন্তু প্রয়োগ করা হবে না (সক্ষম/নিষ্ক্রিয় করতে চেকবক্স টগল করুন)",
        pt: "Filtros desabilitados são salvos mas não serão aplicados (alterne a caixa de seleção para ativar/desativar)",
        ru: "Отключенные фильтры сохраняются, но не применяются (переключите флажок для включения/отключения)",
        ur: "غیر فعال فلٹرز محفوظ ہوتے ہیں لیکن لاگو نہیں ہوں گے (فعال/غیر فعال کرنے کے لیے چیک باکس ٹوگل کریں)",
        id: "Filter yang dinonaktifkan disimpan tetapi tidak akan diterapkan (aktifkan/nonaktifkan kotak centang untuk mengaktifkan/menonaktifkan)",
        de: "Deaktivierte Filter werden gespeichert, aber nicht angewendet (Kontrollkästchen zum Aktivieren/Deaktivieren umschalten)",
        sw: "Vichujio vilivyozimwa vinaokolewa lakini havitatekelezwa (geuza kisanduku cha kuangalia ili kuwezesha/kuzima)",
        mr: "अक्षम केलेले फिल्टर सेव्ह केले जातात परंतु लागू केले जाणार नाहीत (सक्षम/अक्षम करण्यासाठी चेकबॉक्स टॉगल करा)",
      }),
    },
    save: {
      saving: t({
        en: "Saving...",
        zh: "保存中...",
        ja: "保存中...",
        ko: "저장 중...",
        hi: "सहेज रहे हैं...",
        es: "Guardando...",
        fr: "Enregistrement...",
        ar: "جاري الحفظ...",
        bn: "সংরক্ষণ হচ্ছে...",
        pt: "Salvando...",
        ru: "Сохранение...",
        ur: "محفوظ ہو رہا ہے...",
        id: "Menyimpan...",
        de: "Speichern...",
        sw: "Inakohoa...",
        mr: "सेव्ह करत आहे...",
      }),
      saveButton: t({
        en: "Save Preferences",
        zh: "保存偏好设置",
        ja: "設定を保存",
        ko: "환경설정 저장",
        hi: "प्राथमिकताएँ सहेजें",
        es: "Guardar Preferencias",
        fr: "Enregistrer les Préférences",
        ar: "حفظ التفضيلات",
        bn: "পছন্দসমূহ সংরক্ষণ করুন",
        pt: "Salvar Preferências",
        ru: "Сохранить Настройки",
        ur: "ترجیحات محفوظ کریں",
        id: "Simpan Preferensi",
        de: "Einstellungen Speichern",
        sw: "Hifadhi Mapendeleo",
        mr: "प्राधान्ये सेव्ह करा",
      }),
    },
    errors: {
      failedToFetch: t({
        en: "Failed to fetch preferences",
        zh: "无法获取偏好设置",
        ja: "設定の取得に失敗しました",
        ko: "환경설정을 가져오지 못했습니다",
        hi: "प्राथमिकताएँ प्राप्त करने में विफल",
        es: "Error al obtener las preferencias",
        fr: "Échec de la récupération des préférences",
        ar: "فشل في جلب التفضيلات",
        bn: "পছন্দসমূহ আনতে ব্যর্থ",
        pt: "Falha ao buscar preferências",
        ru: "Не удалось получить настройки",
        ur: "ترجیحات حاصل کرنے میں ناکام",
        id: "Gagal mengambil preferensi",
        de: "Fehler beim Abrufen der Einstellungen",
        sw: "Imeshindwa kupata mapendeleo",
        mr: "प्राधान्ये मिळवण्यात अयशस्वी",
      }),
      failedToLoad: t({
        en: "Failed to load preferences",
        zh: "无法加载偏好设置",
        ja: "設定の読み込みに失敗しました",
        ko: "환경설정을 로드하지 못했습니다",
        hi: "प्राथमिकताएँ लोड करने में विफल",
        es: "Error al cargar las preferencias",
        fr: "Échec du chargement des préférences",
        ar: "فشل في تحميل التفضيلات",
        bn: "পছন্দসমূহ লোড করতে ব্যর্থ",
        pt: "Falha ao carregar preferências",
        ru: "Не удалось загрузить настройки",
        ur: "ترجیحات لوڈ کرنے میں ناکام",
        id: "Gagal memuat preferensi",
        de: "Fehler beim Laden der Einstellungen",
        sw: "Imeshindwa kupakia mapendeleo",
        mr: "प्राधान्ये लोड करण्यात अयशस्वी",
      }),
      failedToSave: t({
        en: "Failed to save preferences",
        zh: "无法保存偏好设置",
        ja: "設定の保存に失敗しました",
        ko: "환경설정을 저장하지 못했습니다",
        hi: "प्राथमिकताएँ सहेजने में विफल",
        es: "Error al guardar las preferencias",
        fr: "Échec de l'enregistrement des préférences",
        ar: "فشل في حفظ التفضيلات",
        bn: "পছন্দসমূহ সংরক্ষণ করতে ব্যর্থ",
        pt: "Falha ao salvar preferências",
        ru: "Не удалось сохранить настройки",
        ur: "ترجیحات محفوظ کرنے میں ناکام",
        id: "Gagal menyimpan preferensi",
        de: "Fehler beim Speichern der Einstellungen",
        sw: "Imeshindwa kuhifadhi mapendeleo",
        mr: "प्राधान्ये सेव्ह करण्यात अयशस्वी",
      }),
      invalidRegex: t({
        en: "Invalid regex pattern",
        zh: "无效的正则表达式",
        ja: "無効な正規表現パターン",
        ko: "잘못된 정규식 패턴",
        hi: "अमान्य regex पैटर्न",
        es: "Patrón regex no válido",
        fr: "Modèle regex invalide",
        ar: "نمط regex غير صالح",
        bn: "অবৈধ regex প্যাটার্ন",
        pt: "Padrão regex inválido",
        ru: "Недействительный шаблон regex",
        ur: "غلط regex پیٹرن",
        id: "Pola regex tidak valid",
        de: "Ungültiges Regex-Muster",
        sw: "Muundo wa regex si halali",
        mr: "अवैध regex पॅटर्न",
      }),
    },
    success: {
      saved: t({
        en: "Preferences saved successfully!",
        zh: "偏好设置已成功保存！",
        ja: "設定が正常に保存されました！",
        ko: "환경설정이 성공적으로 저장되었습니다!",
        hi: "प्राथमिकताएँ सफलतापूर्वक सहेजी गईं!",
        es: "¡Preferencias guardadas exitosamente!",
        fr: "Préférences enregistrées avec succès !",
        ar: "تم حفظ التفضيلات بنجاح!",
        bn: "পছন্দসমূহ সফলভাবে সংরক্ষিত হয়েছে!",
        pt: "Preferências salvas com sucesso!",
        ru: "Настройки успешно сохранены!",
        ur: "ترجیحات کامیابی سے محفوظ ہو گئیں!",
        id: "Preferensi berhasil disimpan!",
        de: "Einstellungen erfolgreich gespeichert!",
        sw: "Mapendeleo yamehifadhiwa kwa mafanikio!",
        mr: "प्राधान्ये यशस्वीरित्या सेव्ह केली!",
      }),
    },
    examples: {
      domainRegex: t({
        en: "e.g., .*\\.zhihu\\.com (all zhihu subdomains)",
        zh: "例如，.*\\.zhihu\\.com（所有知乎子域名）",
        ja: "例: .*\\.zhihu\\.com（すべての知乎サブドメイン）",
        ko: "예: .*\\.zhihu\\.com (모든 지후 하위 도메인)",
        hi: "उदा., .*\\.zhihu\\.com (सभी zhihu सबडोमेन)",
        es: "ej., .*\\.zhihu\\.com (todos los subdominios de zhihu)",
        fr: "par ex., .*\\.zhihu\\.com (tous les sous-domaines zhihu)",
        ar: "على سبيل المثال، .*\\.zhihu\\.com (جميع النطاقات الفرعية لـ zhihu)",
        bn: "যেমন, .*\\.zhihu\\.com (সমস্ত zhihu সাবডোমেইন)",
        pt: "ex., .*\\.zhihu\\.com (todos os subdomínios zhihu)",
        ru: "например, .*\\.zhihu\\.com (все поддомены zhihu)",
        ur: "مثلاً، .*\\.zhihu\\.com (تمام zhihu سب ڈومینز)",
        id: "mis., .*\\.zhihu\\.com (semua subdomain zhihu)",
        de: "z.B. .*\\.zhihu\\.com (alle zhihu-Subdomains)",
        sw: "k.m., .*\\.zhihu\\.com (subdomain zote za zhihu)",
        mr: "उदा., .*\\.zhihu\\.com (सर्व zhihu सबडोमेन)",
      }),
      titleRegex: t({
        en: "e.g., [0-9]+ (titles containing numbers)",
        zh: "例如，[0-9]+（包含数字的标题）",
        ja: "例: [0-9]+（数字を含むタイトル）",
        ko: "예: [0-9]+ (숫자가 포함된 제목)",
        hi: "उदा., [0-9]+ (संख्याएं युक्त शीर्षक)",
        es: "ej., [0-9]+ (títulos que contienen números)",
        fr: "par ex., [0-9]+ (titres contenant des chiffres)",
        ar: "على سبيل المثال، [0-9]+ (عناوين تحتوي على أرقام)",
        bn: "যেমন, [0-9]+ (সংখ্যা সম্বলিত শিরোনাম)",
        pt: "ex., [0-9]+ (títulos contendo números)",
        ru: "например, [0-9]+ (заголовки, содержащие цифры)",
        ur: "مثلاً، [0-9]+ (نمبرز پر مشتمل عنوانات)",
        id: "mis., [0-9]+ (judul yang berisi angka)",
        de: "z.B. [0-9]+ (Titel mit Zahlen)",
        sw: "k.m., [0-9]+ (vichwa vyenye nambari)",
        mr: "उदा., [0-9]+ (संख्या असलेली शीर्षके)",
      }),
      urlRegex: t({
        en: "e.g., /watch\\?v= (YouTube videos)",
        zh: "例如，/watch\\?v=（YouTube 视频）",
        ja: "例: /watch\\?v=（YouTube 動画）",
        ko: "예: /watch\\?v= (YouTube 동영상)",
        hi: "उदा., /watch\\?v= (YouTube वीडियो)",
        es: "ej., /watch\\?v= (videos de YouTube)",
        fr: "par ex., /watch\\?v= (vidéos YouTube)",
        ar: "على سبيل المثال، /watch\\?v= (مقاطع فيديو YouTube)",
        bn: "যেমন, /watch\\?v= (YouTube ভিডিও)",
        pt: "ex., /watch\\?v= (vídeos do YouTube)",
        ru: "например, /watch\\?v= (видео YouTube)",
        ur: "مثلاً، /watch\\?v= (YouTube ویڈیوز)",
        id: "mis., /watch\\?v= (video YouTube)",
        de: "z.B. /watch\\?v= (YouTube-Videos)",
        sw: "k.m., /watch\\?v= (video za YouTube)",
        mr: "उदा., /watch\\?v= (YouTube व्हिडिओ)",
      }),
      domainPlain: t({
        en: "e.g., zhihu.com, twitter.com",
        zh: "例如，zhihu.com、twitter.com",
        ja: "例: zhihu.com、twitter.com",
        ko: "예: zhihu.com, twitter.com",
        hi: "उदा., zhihu.com, twitter.com",
        es: "ej., zhihu.com, twitter.com",
        fr: "par ex., zhihu.com, twitter.com",
        ar: "على سبيل المثال، zhihu.com، twitter.com",
        bn: "যেমন, zhihu.com, twitter.com",
        pt: "ex., zhihu.com, twitter.com",
        ru: "например, zhihu.com, twitter.com",
        ur: "مثلاً، zhihu.com، twitter.com",
        id: "mis., zhihu.com, twitter.com",
        de: "z.B. zhihu.com, twitter.com",
        sw: "k.m., zhihu.com, twitter.com",
        mr: "उदा., zhihu.com, twitter.com",
      }),
      titlePlain: t({
        en: 'e.g., "draft", "todo" (matches titles containing these words)',
        zh: '例如，"draft"、"todo"（匹配包含这些词的标题）',
        ja: '例: "draft"、"todo"（これらの単語を含むタイトルに一致）',
        ko: '예: "draft", "todo" (이 단어가 포함된 제목과 일치)',
        hi: 'उदा., "draft", "todo" (इन शब्दों युक्त शीर्षकों से मेल खाता है)',
        es: 'ej., "draft", "todo" (coincide con títulos que contienen estas palabras)',
        fr: 'par ex., "draft", "todo" (correspond aux titres contenant ces mots)',
        ar: 'على سبيل المثال، "draft"، "todo" (يطابق العناوين التي تحتوي على هذه الكلمات)',
        bn: 'যেমন, "draft", "todo" (এই শব্দগুলি সম্বলিত শিরোনামের সাথে মেলে)',
        pt: 'ex., "draft", "todo" (corresponde a títulos contendo essas palavras)',
        ru: 'например, "draft", "todo" (соответствует заголовкам, содержащим эти слова)',
        ur: 'مثلاً، "draft"، "todo" (ان الفاظ پر مشتمل عنوانات سے میل کھاتا ہے)',
        id: 'mis., "draft", "todo" (cocok dengan judul yang berisi kata-kata ini)',
        de: 'z.B. "draft", "todo" (passt zu Titeln mit diesen Wörtern)',
        sw: 'k.m., "draft", "todo" (inaingiana na vichwa vyenye maneno haya)',
        mr: 'उदा., "draft", "todo" (या शब्दांसह शीर्षकांशी जुळते)',
      }),
      urlPlain: t({
        en: 'e.g., "/admin", "?debug=" (matches URLs containing these)',
        zh: '例如，"/admin"、"?debug="（匹配包含这些的 URL）',
        ja: '例: "/admin"、"?debug="（これらを含む URL に一致）',
        ko: '예: "/admin", "?debug=" (이를 포함하는 URL과 일치)',
        hi: 'उदा., "/admin", "?debug=" (इन युक्त URL से मेल खाता है)',
        es: 'ej., "/admin", "?debug=" (coincide con URLs que contienen esto)',
        fr: 'par ex., "/admin", "?debug=" (correspond aux URL contenant ceci)',
        ar: 'على سبيل المثال، "/admin"، "?debug=" (يطابق عناوين URL التي تحتوي على هذا)',
        bn: 'যেমন, "/admin", "?debug=" (এগুলি সম্বলিত URL এর সাথে মেলে)',
        pt: 'ex., "/admin", "?debug=" (corresponde a URLs contendo isso)',
        ru: 'например, "/admin", "?debug=" (соответствует URL, содержащим это)',
        ur: 'مثلاً، "/admin"، "?debug=" (ان پر مشتمل URLs سے میل کھاتا ہے)',
        id: 'mis., "/admin", "?debug=" (cocok dengan URL yang berisi ini)',
        de: 'z.B. "/admin", "?debug=" (passt zu URLs, die dies enthalten)',
        sw: 'k.m., "/admin", "?debug=" (inaingiana na URL zenye hizi)',
        mr: 'उदा., "/admin", "?debug=" (हे असलेल्या URL शी जुळते)',
      }),
    },
  },
} satisfies DeclarationContent;

export default preferencesPageContent;
