import { t, type DeclarationContent } from "intlayer";

const listPageContent = {
  key: "list-page",
  content: {
    metadata: {
      title: t({
        en: "Lianki - Learning Dashboard",
        zh: "Lianki - 学习仪表板",
        ja: "Lianki - 学習ダッシュボード",
        ko: "Lianki - 학습 대시보드",
        hi: "Lianki - शिक्षा डैशबोर्ड",
        es: "Lianki - Panel de Aprendizaje",
        fr: "Lianki - Tableau de Bord d'Apprentissage",
        ar: "Lianki - لوحة التعلم",
        bn: "Lianki - শেখার ড্যাশবোর্ড",
        pt: "Lianki - Painel de Aprendizagem",
        ru: "Lianki - Панель Обучения",
        ur: "Lianki - سیکھنے کا ڈیش بورڈ",
        id: "Lianki - Dasbor Pembelajaran",
        de: "Lianki - Lern-Dashboard",
        sw: "Lianki - Dashibodi ya Kujifunza",
        mr: "Lianki - शिक्षण डॅशबोर्ड",
      }),
      description: t({
        en: "Manage your flashcards and track your learning progress",
        zh: "管理您的抽认卡并跟踪学习进度",
        ja: "フラッシュカードを管理して学習の進捗を追跡",
        ko: "플래시카드를 관리하고 학습 진행 상황을 추적하세요",
        hi: "अपने फ्लैशकार्ड प्रबंधित करें और अपनी सीखने की प्रगति को ट्रैक करें",
        es: "Administra tus tarjetas didácticas y rastrea tu progreso de aprendizaje",
        fr: "Gérez vos cartes mémoire et suivez vos progrès d'apprentissage",
        ar: "إدارة بطاقاتك التعليمية وتتبع تقدم التعلم",
        bn: "আপনার ফ্ল্যাশকার্ড পরিচালনা করুন এবং আপনার শেখার অগ্রগতি ট্র্যাক করুন",
        pt: "Gerencie seus flashcards e acompanhe seu progresso de aprendizagem",
        ru: "Управляйте своими карточками и отслеживайте прогресс в обучении",
        ur: "اپنے فلیش کارڈز کا انتظام کریں اور اپنی سیکھنے کی پیش رفت کو ٹریک کریں",
        id: "Kelola kartu flash Anda dan lacak kemajuan belajar Anda",
        de: "Verwalten Sie Ihre Lernkarten und verfolgen Sie Ihren Lernfortschritt",
        sw: "Dhibiti kadi zako za kumbukumbu na ufuatilie maendeleo yako ya kujifunza",
        mr: "आपले फ्लॅशकार्ड व्यवस्थापित करा आणि आपल्या शिकण्याची प्रगती ट्रॅक करा",
      }),
    },
    nextCard: t({
      en: "Next card",
      zh: "下一张卡片",
      ja: "次のカード",
      ko: "다음 카드",
      hi: "अगला कार्ड",
      es: "Siguiente tarjeta",
      fr: "Carte suivante",
      ar: "البطاقة التالية",
      bn: "পরবর্তী কার্ড",
      pt: "Próximo cartão",
      ru: "Следующая карточка",
      ur: "اگلا کارڈ",
      id: "Kartu berikutnya",
      de: "Nächste Karte",
      sw: "Kadi inayofuata",
      mr: "पुढील कार्ड",
    }),
    totalCards: t({
      en: "Total cards:",
      zh: "总卡片数：",
      ja: "総カード数：",
      ko: "총 카드:",
      hi: "कुल कार्ड:",
      es: "Total de tarjetas:",
      fr: "Total de cartes:",
      ar: "إجمالي البطاقات:",
      bn: "মোট কার্ড:",
      pt: "Total de cartões:",
      ru: "Всего карточек:",
      ur: "کل کارڈز:",
      id: "Total kartu:",
      de: "Gesamtzahl der Karten:",
      sw: "Jumla ya kadi:",
      mr: "एकूण कार्ड:",
    }),
    dueCards: t({
      en: "Due cards:",
      zh: "到期卡片：",
      ja: "復習予定カード：",
      ko: "복습 예정 카드:",
      hi: "देय कार्ड:",
      es: "Tarjetas pendientes:",
      fr: "Cartes à réviser:",
      ar: "البطاقات المستحقة:",
      bn: "পর্যালোচনা করার কার্ড:",
      pt: "Cartões devidos:",
      ru: "Карточки к повторению:",
      ur: "واجب الادا کارڈز:",
      id: "Kartu jatuh tempo:",
      de: "Fällige Karten:",
      sw: "Kadi zinazostahili:",
      mr: "देय कार्ड:",
    }),
    learningActivity: t({
      en: "Learning Activity",
      zh: "学习活动",
      ja: "学習アクティビティ",
      ko: "학습 활동",
      hi: "सीखने की गतिविधि",
      es: "Actividad de Aprendizaje",
      fr: "Activité d'Apprentissage",
      ar: "نشاط التعلم",
      bn: "শেখার কার্যকলাপ",
      pt: "Atividade de Aprendizagem",
      ru: "Учебная Активность",
      ur: "سیکھنے کی سرگرمی",
      id: "Aktivitas Pembelajaran",
      de: "Lernaktivität",
      sw: "Shughuli za Kujifunza",
      mr: "शिकण्याची क्रिया",
    }),
    deleteCard: t({
      en: "Delete card:",
      zh: "删除卡片：",
      ja: "カードを削除:",
      ko: "카드 삭제:",
      hi: "कार्ड हटाएं:",
      es: "Eliminar tarjeta:",
      fr: "Supprimer la carte:",
      ar: "حذف البطاقة:",
      bn: "কার্ড মুছুন:",
      pt: "Excluir cartão:",
      ru: "Удалить карточку:",
      ur: "کارڈ حذف کریں:",
      id: "Hapus kartu:",
      de: "Karte löschen:",
      sw: "Futa kadi:",
      mr: "कार्ड हटवा:",
    }),
    deleteCardTitle: t({
      en: "Delete this card",
      zh: "删除此卡片",
      ja: "このカードを削除",
      ko: "이 카드 삭제",
      hi: "इस कार्ड को हटाएं",
      es: "Eliminar esta tarjeta",
      fr: "Supprimer cette carte",
      ar: "حذف هذه البطاقة",
      bn: "এই কার্ডটি মুছুন",
      pt: "Excluir este cartão",
      ru: "Удалить эту карточку",
      ur: "یہ کارڈ حذف کریں",
      id: "Hapus kartu ini",
      de: "Diese Karte löschen",
      sw: "Futa kadi hii",
      mr: "हे कार्ड हटवा",
    }),
    deleteFailedAlert: t({
      en: "Failed to delete card",
      zh: "删除卡片失败",
      ja: "カードの削除に失敗しました",
      ko: "카드 삭제 실패",
      hi: "कार्ड हटाने में विफल",
      es: "Error al eliminar la tarjeta",
      fr: "Échec de la suppression de la carte",
      ar: "فشل حذف البطاقة",
      bn: "কার্ড মুছতে ব্যর্থ",
      pt: "Falha ao excluir o cartão",
      ru: "Не удалось удалить карточку",
      ur: "کارڈ حذف کرنے میں ناکام",
      id: "Gagal menghapus kartu",
      de: "Fehler beim Löschen der Karte",
      sw: "Imeshindwa kufuta kadi",
      mr: "कार्ड हटवण्यात अयशस्वी",
    }),
    deleteErrorAlert: t({
      en: "Error deleting card",
      zh: "删除卡片时出错",
      ja: "カード削除エラー",
      ko: "카드 삭제 오류",
      hi: "कार्ड हटाने में त्रुटि",
      es: "Error al eliminar la tarjeta",
      fr: "Erreur lors de la suppression de la carte",
      ar: "خطأ في حذف البطاقة",
      bn: "কার্ড মুছতে ত্রুটি",
      pt: "Erro ao excluir cartão",
      ru: "Ошибка удаления карточки",
      ur: "کارڈ حذف کرنے میں خرابی",
      id: "Kesalahan menghapus kartu",
      de: "Fehler beim Löschen der Karte",
      sw: "Hitilafu katika kufuta kadi",
      mr: "कार्ड हटवताना त्रुटी",
    }),
    refresh: t({
      en: "↻ Refresh",
      zh: "↻ 刷新",
      ja: "↻ 更新",
      ko: "↻ 새로고침",
      hi: "↻ ताज़ा करें",
      es: "↻ Actualizar",
      fr: "↻ Rafraîchir",
      ar: "↻ تحديث",
      bn: "↻ রিফ্রেশ",
      pt: "↻ Atualizar",
      ru: "↻ Обновить",
      ur: "↻ تازہ کریں",
      id: "↻ Segarkan",
      de: "↻ Aktualisieren",
      sw: "↻ Onyesha upya",
      mr: "↻ रिफ्रेश",
    }),
    refreshing: t({
      en: "Refreshing...",
      zh: "刷新中...",
      ja: "更新中...",
      ko: "새로고침 중...",
      hi: "ताज़ा हो रहा है...",
      es: "Actualizando...",
      fr: "Actualisation...",
      ar: "جاري التحديث...",
      bn: "রিফ্রেশ করা হচ্ছে...",
      pt: "Atualizando...",
      ru: "Обновление...",
      ur: "تازہ ہو رہا ہے...",
      id: "Menyegarkan...",
      de: "Aktualisiere...",
      sw: "Inaonyesha upya...",
      mr: "रिफ्रेश होत आहे...",
    }),
    refreshHeatmapTitle: t({
      en: "Refresh heatmap to show latest reviews",
      zh: "刷新热力图以显示最新评论",
      ja: "ヒートマップを更新して最新のレビューを表示",
      ko: "최신 리뷰를 표시하기 위해 히트맵 새로고침",
      hi: "नवीनतम समीक्षाएं दिखाने के लिए हीटमैप ताज़ा करें",
      es: "Actualizar mapa de calor para mostrar las últimas revisiones",
      fr: "Actualiser la carte thermique pour afficher les dernières révisions",
      ar: "تحديث الخريطة الحرارية لإظهار المراجعات الأخيرة",
      bn: "সর্বশেষ পর্যালোচনা দেখাতে হিটম্যাপ রিফ্রেশ করুন",
      pt: "Atualizar mapa de calor para mostrar as últimas revisões",
      ru: "Обновить тепловую карту для отображения последних повторений",
      ur: "تازہ ترین جائزوں کو دکھانے کے لیے ہیٹ میپ تازہ کریں",
      id: "Segarkan peta panas untuk menampilkan ulasan terbaru",
      de: "Heatmap aktualisieren, um die neuesten Überprüfungen anzuzeigen",
      sw: "Onyesha upya ramani ya joto ili kuonyesha mapitio ya hivi karibuni",
      mr: "नवीनतम पुनरावलोकने दाखवण्यासाठी हीटमॅप रिफ्रेश करा",
    }),
  },
} satisfies DeclarationContent;

export default listPageContent;
