import { t, type DeclarationContent } from "intlayer";

const learnPageContent = {
  key: "learn-page",
  content: {
    metadata: {
      title: t({
        en: "Learn - Lianki",
        zh: "学习 - Lianki",
        ja: "学習 - Lianki",
        ko: "학습 - Lianki",
        hi: "सीखें - Lianki",
        es: "Aprender - Lianki",
        fr: "Apprendre - Lianki",
        ar: "تعلم - Lianki",
        bn: "শিখুন - Lianki",
        pt: "Aprender - Lianki",
        ru: "Обучение - Lianki",
        ur: "سیکھیں - Lianki",
        id: "Belajar - Lianki",
        de: "Lernen - Lianki",
        sw: "Jifunze - Lianki",
        mr: "शिका - Lianki",
      }),
      description: t({
        en: "Import materials from recommended lists, YouTube playlists, or custom URLs",
        zh: "从推荐列表、YouTube 播放列表或自定义 URL 导入材料",
        ja: "おすすめリスト、YouTube プレイリスト、カスタム URL から教材をインポート",
        ko: "추천 목록, YouTube 재생목록 또는 사용자 지정 URL에서 자료 가져오기",
        hi: "अनुशंसित सूचियों, YouTube प्लेलिस्ट या कस्टम URL से सामग्री आयात करें",
        es: "Importa materiales de listas recomendadas, listas de reproducción de YouTube o URLs personalizadas",
        fr: "Importez du matériel à partir de listes recommandées, de listes de lecture YouTube ou d'URL personnalisées",
        ar: "استيراد المواد من القوائم الموصى بها أو قوائم تشغيل YouTube أو عناوين URL المخصصة",
        bn: "প্রস্তাবিত তালিকা, YouTube প্লেলিস্ট বা কাস্টম URL থেকে উপকরণ আমদানি করুন",
        pt: "Importe materiais de listas recomendadas, playlists do YouTube ou URLs personalizadas",
        ru: "Импортируйте материалы из рекомендованных списков, плейлистов YouTube или пользовательских URL",
        ur: "تجویز کردہ فہرستوں، YouTube پلے لسٹس، یا اپنی مرضی کے URL سے مواد درآمد کریں",
        id: "Impor materi dari daftar yang direkomendasikan, playlist YouTube, atau URL kustom",
        de: "Importieren Sie Materialien aus empfohlenen Listen, YouTube-Playlists oder benutzerdefinierten URLs",
        sw: "Leta nyenzo kutoka orodha zilizopendekezwa, orodha za kucheza za YouTube, au URL maalum",
        mr: "शिफारस केलेल्या यादी, YouTube प्लेलिस्ट किंवा सानुकूल URL वरून साहित्य आयात करा",
      }),
    },
    heading: t({
      en: "Import Learning Materials",
      zh: "导入学习材料",
      ja: "学習教材をインポート",
      ko: "학습 자료 가져오기",
      hi: "सीखने की सामग्री आयात करें",
      es: "Importar Materiales de Aprendizaje",
      fr: "Importer du Matériel d'Apprentissage",
      ar: "استيراد مواد التعلم",
      bn: "শেখার উপকরণ আমদানি করুন",
      pt: "Importar Materiais de Aprendizado",
      ru: "Импорт Учебных Материалов",
      ur: "سیکھنے کا مواد درآمد کریں",
      id: "Impor Materi Pembelajaran",
      de: "Lernmaterialien Importieren",
      sw: "Leta Nyenzo za Kujifunza",
      mr: "शिकण्याची साहित्ये आयात करा",
    }),
    subtitle: t({
      en: "Start learning by importing materials from recommended lists",
      zh: "通过从推荐列表导入材料开始学习",
      ja: "おすすめリストから教材をインポートして学習を開始",
      ko: "추천 목록에서 자료를 가져와서 학습 시작",
      hi: "अनुशंसित सूचियों से सामग्री आयात करके सीखना शुरू करें",
      es: "Comienza a aprender importando materiales de listas recomendadas",
      fr: "Commencez à apprendre en important du matériel à partir de listes recommandées",
      ar: "ابدأ التعلم عن طريق استيراد المواد من القوائم الموصى بها",
      bn: "প্রস্তাবিত তালিকা থেকে উপকরণ আমদানি করে শেখা শুরু করুন",
      pt: "Comece a aprender importando materiais de listas recomendadas",
      ru: "Начните обучение, импортируя материалы из рекомендованных списков",
      ur: "تجویز کردہ فہرستوں سے مواد درآمد کرکے سیکھنا شروع کریں",
      id: "Mulai belajar dengan mengimpor materi dari daftar yang direkomendasikan",
      de: "Beginnen Sie zu lernen, indem Sie Materialien aus empfohlenen Listen importieren",
      sw: "Anza kujifunza kwa kuleta nyenzo kutoka orodha zilizopendekezwa",
      mr: "शिफारस केलेल्या यादींमधून साहित्य आयात करून शिकणे सुरू करा",
    }),
    subtitleYoutube: t({
      en: ", YouTube playlists,",
      zh: "、YouTube 播放列表",
      ja: "、YouTube プレイリスト、",
      ko: ", YouTube 재생목록,",
      hi: ", YouTube प्लेलिस्ट,",
      es: ", listas de reproducción de YouTube,",
      fr: ", listes de lecture YouTube,",
      ar: "، قوائم تشغيل YouTube،",
      bn: ", YouTube প্লেলিস্ট,",
      pt: ", playlists do YouTube,",
      ru: ", плейлисты YouTube,",
      ur: "، YouTube پلے لسٹس،",
      id: ", playlist YouTube,",
      de: ", YouTube-Playlists,",
      sw: ", orodha za kucheza za YouTube,",
      mr: ", YouTube प्लेलिस्ट,",
    }),
    subtitleEnd: t({
      en: " or custom URL lists.",
      zh: "或自定义 URL 列表。",
      ja: "またはカスタム URL リストから。",
      ko: " 또는 사용자 지정 URL 목록에서 가져올 수 있습니다.",
      hi: " या कस्टम URL सूचियों से।",
      es: " o listas de URL personalizadas.",
      fr: " ou listes d'URL personnalisées.",
      ar: " أو قوائم URL المخصصة.",
      bn: " বা কাস্টম URL তালিকা থেকে।",
      pt: " ou listas de URLs personalizadas.",
      ru: " или пользовательские списки URL.",
      ur: " یا اپنی مرضی کی URL فہرستوں سے۔",
      id: " atau daftar URL kustom.",
      de: " oder benutzerdefinierte URL-Listen.",
      sw: " au orodha za URL maalum.",
      mr: " किंवा सानुकूल URL यादी.",
    }),
    tabs: {
      recommended: t({
        en: "Recommended Lists",
        zh: "推荐列表",
        ja: "おすすめリスト",
        ko: "추천 목록",
        hi: "अनुशंसित सूचियाँ",
        es: "Listas Recomendadas",
        fr: "Listes Recommandées",
        ar: "القوائم الموصى بها",
        bn: "প্রস্তাবিত তালিকা",
        pt: "Listas Recomendadas",
        ru: "Рекомендованные Списки",
        ur: "تجویز کردہ فہرستیں",
        id: "Daftar yang Direkomendasikan",
        de: "Empfohlene Listen",
        sw: "Orodha Zilizopendekezwa",
        mr: "शिफारस केलेल्या यादी",
      }),
      customUrl: t({
        en: "Custom URL List",
        zh: "自定义 URL 列表",
        ja: "カスタム URL リスト",
        ko: "사용자 지정 URL 목록",
        hi: "कस्टम URL सूची",
        es: "Lista de URL Personalizada",
        fr: "Liste d'URL Personnalisée",
        ar: "قائمة URL المخصصة",
        bn: "কাস্টম URL তালিকা",
        pt: "Lista de URLs Personalizada",
        ru: "Пользовательский Список URL",
        ur: "اپنی مرضی کی URL فہرست",
        id: "Daftar URL Kustom",
        de: "Benutzerdefinierte URL-Liste",
        sw: "Orodha ya URL Maalum",
        mr: "सानुकूल URL यादी",
      }),
      youtube: t({
        en: "YouTube Playlist",
        zh: "YouTube 播放列表",
        ja: "YouTube プレイリスト",
        ko: "YouTube 재생목록",
        hi: "YouTube प्लेलिस्ट",
        es: "Lista de Reproducción de YouTube",
        fr: "Liste de Lecture YouTube",
        ar: "قائمة تشغيل YouTube",
        bn: "YouTube প্লেলিস্ট",
        pt: "Playlist do YouTube",
        ru: "Плейлист YouTube",
        ur: "YouTube پلے لسٹ",
        id: "Playlist YouTube",
        de: "YouTube-Playlist",
        sw: "Orodha ya Kucheza ya YouTube",
        mr: "YouTube प्लेलिस्ट",
      }),
    },
    recommended: {
      heading: t({
        en: "Recommended Learning Materials",
        zh: "推荐学习材料",
        ja: "おすすめの学習教材",
        ko: "추천 학습 자료",
        hi: "अनुशंसित शिक्षण सामग्री",
        es: "Materiales de Aprendizaje Recomendados",
        fr: "Matériel d'Apprentissage Recommandé",
        ar: "مواد التعلم الموصى بها",
        bn: "প্রস্তাবিত শিক্ষা উপকরণ",
        pt: "Materiais de Aprendizado Recomendados",
        ru: "Рекомендованные Учебные Материалы",
        ur: "تجویز کردہ تعلیمی مواد",
        id: "Materi Pembelajaran yang Direkomendasikan",
        de: "Empfohlene Lernmaterialien",
        sw: "Nyenzo za Kujifunza Zilizopendekezwa",
        mr: "शिफारस केलेली शिक्षण साहित्ये",
      }),
      viewButton: t({
        en: "View Materials →",
        zh: "查看材料 →",
        ja: "教材を見る →",
        ko: "자료 보기 →",
        hi: "सामग्री देखें →",
        es: "Ver Materiales →",
        fr: "Voir le Matériel →",
        ar: "عرض المواد →",
        bn: "উপকরণ দেখুন →",
        pt: "Ver Materiais →",
        ru: "Посмотреть Материалы →",
        ur: "مواد دیکھیں →",
        id: "Lihat Materi →",
        de: "Materialien Ansehen →",
        sw: "Tazama Nyenzo →",
        mr: "साहित्य पहा →",
      }),
    },
    customUrl: {
      heading: t({
        en: "Import from Custom URL List",
        zh: "从自定义 URL 列表导入",
        ja: "カスタム URL リストからインポート",
        ko: "사용자 지정 URL 목록에서 가져오기",
        hi: "कस्टम URL सूची से आयात करें",
        es: "Importar desde Lista de URL Personalizada",
        fr: "Importer depuis une Liste d'URL Personnalisée",
        ar: "استيراد من قائمة URL المخصصة",
        bn: "কাস্টম URL তালিকা থেকে আমদানি করুন",
        pt: "Importar de Lista de URLs Personalizada",
        ru: "Импорт из Пользовательского Списка URL",
        ur: "اپنی مرضی کی URL فہرست سے درآمد کریں",
        id: "Impor dari Daftar URL Kustom",
        de: "Aus Benutzerdefinierter URL-Liste Importieren",
        sw: "Leta kutoka Orodha ya URL Maalum",
        mr: "सानुकूल URL यादीतून आयात करा",
      }),
      description: t({
        en: "Enter a URL to a .txt file containing one URL per line. Each URL will be added to your learning queue.",
        zh: "输入包含每行一个 URL 的 .txt 文件的 URL。每个 URL 将添加到您的学习队列中。",
        ja: "1 行に 1 つの URL を含む .txt ファイルの URL を入力してください。各 URL は学習キューに追加されます。",
        ko: "한 줄에 하나의 URL이 포함된 .txt 파일의 URL을 입력하세요. 각 URL이 학습 대기열에 추가됩니다.",
        hi: "प्रति पंक्ति एक URL युक्त .txt फ़ाइल का URL दर्ज करें। प्रत्येक URL आपकी सीखने की कतार में जोड़ा जाएगा।",
        es: "Ingresa una URL a un archivo .txt que contenga una URL por línea. Cada URL se agregará a tu cola de aprendizaje.",
        fr: "Entrez une URL vers un fichier .txt contenant une URL par ligne. Chaque URL sera ajoutée à votre file d'apprentissage.",
        ar: "أدخل عنوان URL لملف .txt يحتوي على عنوان URL واحد لكل سطر. سيتم إضافة كل عنوان URL إلى قائمة التعلم الخاصة بك.",
        bn: "প্রতি লাইনে একটি URL সম্বলিত .txt ফাইলের URL লিখুন। প্রতিটি URL আপনার শেখার সারিতে যোগ করা হবে।",
        pt: "Insira uma URL para um arquivo .txt contendo uma URL por linha. Cada URL será adicionada à sua fila de aprendizado.",
        ru: "Введите URL файла .txt, содержащего один URL в каждой строке. Каждый URL будет добавлен в вашу очередь обучения.",
        ur: "ہر لائن میں ایک URL پر مشتمل .txt فائل کا URL درج کریں۔ ہر URL آپ کی سیکھنے کی قطار میں شامل کیا جائے گا۔",
        id: "Masukkan URL ke file .txt yang berisi satu URL per baris. Setiap URL akan ditambahkan ke antrean belajar Anda.",
        de: "Geben Sie eine URL zu einer .txt-Datei ein, die eine URL pro Zeile enthält. Jede URL wird Ihrer Lernwarteschlange hinzugefügt.",
        sw: "Ingiza URL ya faili la .txt yenye URL moja kwa mstari. Kila URL itaongezwa kwenye foleni yako ya kujifunza.",
        mr: "प्रत्येक ओळीत एक URL असलेल्या .txt फाइलचा URL प्रविष्ट करा। प्रत्येक URL तुमच्या शिकण्याच्या रांगेत जोडला जाईल.",
      }),
      label: t({
        en: "Text File URL",
        zh: "文本文件 URL",
        ja: "テキストファイル URL",
        ko: "텍스트 파일 URL",
        hi: "टेक्स्ट फ़ाइल URL",
        es: "URL del Archivo de Texto",
        fr: "URL du Fichier Texte",
        ar: "URL ملف النص",
        bn: "টেক্সট ফাইল URL",
        pt: "URL do Arquivo de Texto",
        ru: "URL Текстового Файла",
        ur: "ٹیکسٹ فائل URL",
        id: "URL File Teks",
        de: "Textdatei-URL",
        sw: "URL ya Faili la Maandishi",
        mr: "मजकूर फाइल URL",
      }),
      placeholder: t({
        en: "https://example.com/urls.txt",
        zh: "https://example.com/urls.txt",
        ja: "https://example.com/urls.txt",
        ko: "https://example.com/urls.txt",
        hi: "https://example.com/urls.txt",
        es: "https://example.com/urls.txt",
        fr: "https://example.com/urls.txt",
        ar: "https://example.com/urls.txt",
        bn: "https://example.com/urls.txt",
        pt: "https://example.com/urls.txt",
        ru: "https://example.com/urls.txt",
        ur: "https://example.com/urls.txt",
        id: "https://example.com/urls.txt",
        de: "https://example.com/urls.txt",
        sw: "https://example.com/urls.txt",
        mr: "https://example.com/urls.txt",
      }),
      exampleLabel: t({
        en: "Example file format:",
        zh: "示例文件格式：",
        ja: "ファイル形式の例：",
        ko: "파일 형식 예시:",
        hi: "उदाहरण फ़ाइल प्रारूप:",
        es: "Formato de archivo de ejemplo:",
        fr: "Format de fichier d'exemple:",
        ar: "تنسيق ملف المثال:",
        bn: "উদাহরণ ফাইল ফরম্যাট:",
        pt: "Formato de arquivo de exemplo:",
        ru: "Пример формата файла:",
        ur: "مثال فائل فارمیٹ:",
        id: "Format file contoh:",
        de: "Beispiel-Dateiformat:",
        sw: "Muundo wa faili la mfano:",
        mr: "उदाहरण फाइल स्वरूप:",
      }),
      importing: t({
        en: "Importing...",
        zh: "导入中...",
        ja: "インポート中...",
        ko: "가져오는 중...",
        hi: "आयात हो रहा है...",
        es: "Importando...",
        fr: "Importation en cours...",
        ar: "جاري الاستيراد...",
        bn: "আমদানি হচ্ছে...",
        pt: "Importando...",
        ru: "Импорт...",
        ur: "درآمد ہو رہی ہے...",
        id: "Mengimpor...",
        de: "Importiere...",
        sw: "Inaboresha...",
        mr: "आयात करत आहे...",
      }),
      importButton: t({
        en: "Import URLs",
        zh: "导入 URL",
        ja: "URL をインポート",
        ko: "URL 가져오기",
        hi: "URL आयात करें",
        es: "Importar URLs",
        fr: "Importer des URLs",
        ar: "استيراد URLs",
        bn: "URL আমদানি করুন",
        pt: "Importar URLs",
        ru: "Импортировать URL",
        ur: "URL درآمد کریں",
        id: "Impor URL",
        de: "URLs Importieren",
        sw: "Leta URL",
        mr: "URL आयात करा",
      }),
    },
    youtube: {
      heading: t({
        en: "Import from YouTube Playlist",
        zh: "从 YouTube 播放列表导入",
        ja: "YouTube プレイリストからインポート",
        ko: "YouTube 재생목록에서 가져오기",
        hi: "YouTube प्लेलिस्ट से आयात करें",
        es: "Importar desde Lista de Reproducción de YouTube",
        fr: "Importer depuis une Liste de Lecture YouTube",
        ar: "استيراد من قائمة تشغيل YouTube",
        bn: "YouTube প্লেলিস্ট থেকে আমদানি করুন",
        pt: "Importar de Playlist do YouTube",
        ru: "Импорт из Плейлиста YouTube",
        ur: "YouTube پلے لسٹ سے درآمد کریں",
        id: "Impor dari Playlist YouTube",
        de: "Aus YouTube-Playlist Importieren",
        sw: "Leta kutoka Orodha ya Kucheza ya YouTube",
        mr: "YouTube प्लेलिस्ट वरून आयात करा",
      }),
      description: t({
        en: "Enter a YouTube playlist URL. All videos in the playlist will be added to your learning queue.",
        zh: "输入 YouTube 播放列表 URL。播放列表中的所有视频将添加到您的学习队列中。",
        ja: "YouTube プレイリストの URL を入力してください。プレイリスト内のすべての動画が学習キューに追加されます。",
        ko: "YouTube 재생목록 URL을 입력하세요. 재생목록의 모든 동영상이 학습 대기열에 추가됩니다.",
        hi: "YouTube प्लेलिस्ट URL दर्ज करें। प्लेलिस्ट में सभी वीडियो आपकी सीखने की कतार में जोड़े जाएंगे।",
        es: "Ingresa una URL de lista de reproducción de YouTube. Todos los videos de la lista se agregarán a tu cola de aprendizaje.",
        fr: "Entrez une URL de liste de lecture YouTube. Toutes les vidéos de la liste seront ajoutées à votre file d'apprentissage.",
        ar: "أدخل عنوان URL لقائمة تشغيل YouTube. ستتم إضافة جميع مقاطع الفيديو في القائمة إلى قائمة التعلم الخاصة بك.",
        bn: "YouTube প্লেলিস্ট URL লিখুন। প্লেলিস্টের সমস্ত ভিডিও আপনার শেখার সারিতে যোগ করা হবে।",
        pt: "Insira uma URL de playlist do YouTube. Todos os vídeos da playlist serão adicionados à sua fila de aprendizado.",
        ru: "Введите URL плейлиста YouTube. Все видео из плейлиста будут добавлены в вашу очередь обучения.",
        ur: "YouTube پلے لسٹ کا URL درج کریں۔ پلے لسٹ کی تمام ویڈیوز آپ کی سیکھنے کی قطار میں شامل کی جائیں گی۔",
        id: "Masukkan URL playlist YouTube. Semua video dalam playlist akan ditambahkan ke antrean belajar Anda.",
        de: "Geben Sie eine YouTube-Playlist-URL ein. Alle Videos in der Playlist werden Ihrer Lernwarteschlange hinzugefügt.",
        sw: "Ingiza URL ya orodha ya kucheza ya YouTube. Video zote kwenye orodha zitaongezwa kwenye foleni yako ya kujifunza.",
        mr: "YouTube प्लेलिस्ट URL प्रविष्ट करा. प्लेलिस्टमधील सर्व व्हिडिओ तुमच्या शिकण्याच्या रांगेत जोडले जातील.",
      }),
      label: t({
        en: "YouTube Playlist URL",
        zh: "YouTube 播放列表 URL",
        ja: "YouTube プレイリスト URL",
        ko: "YouTube 재생목록 URL",
        hi: "YouTube प्लेलिस्ट URL",
        es: "URL de Lista de Reproducción de YouTube",
        fr: "URL de Liste de Lecture YouTube",
        ar: "URL قائمة تشغيل YouTube",
        bn: "YouTube প্লেলিস্ট URL",
        pt: "URL da Playlist do YouTube",
        ru: "URL Плейлиста YouTube",
        ur: "YouTube پلے لسٹ URL",
        id: "URL Playlist YouTube",
        de: "YouTube-Playlist-URL",
        sw: "URL ya Orodha ya Kucheza ya YouTube",
        mr: "YouTube प्लेलिस्ट URL",
      }),
      placeholder: t({
        en: "https://www.youtube.com/playlist?list=PLxxx...",
        zh: "https://www.youtube.com/playlist?list=PLxxx...",
        ja: "https://www.youtube.com/playlist?list=PLxxx...",
        ko: "https://www.youtube.com/playlist?list=PLxxx...",
        hi: "https://www.youtube.com/playlist?list=PLxxx...",
        es: "https://www.youtube.com/playlist?list=PLxxx...",
        fr: "https://www.youtube.com/playlist?list=PLxxx...",
        ar: "https://www.youtube.com/playlist?list=PLxxx...",
        bn: "https://www.youtube.com/playlist?list=PLxxx...",
        pt: "https://www.youtube.com/playlist?list=PLxxx...",
        ru: "https://www.youtube.com/playlist?list=PLxxx...",
        ur: "https://www.youtube.com/playlist?list=PLxxx...",
        id: "https://www.youtube.com/playlist?list=PLxxx...",
        de: "https://www.youtube.com/playlist?list=PLxxx...",
        sw: "https://www.youtube.com/playlist?list=PLxxx...",
        mr: "https://www.youtube.com/playlist?list=PLxxx...",
      }),
      exampleLabel: t({
        en: "Example:",
        zh: "示例：",
        ja: "例：",
        ko: "예시:",
        hi: "उदाहरण:",
        es: "Ejemplo:",
        fr: "Exemple:",
        ar: "مثال:",
        bn: "উদাহরণ:",
        pt: "Exemplo:",
        ru: "Пример:",
        ur: "مثال:",
        id: "Contoh:",
        de: "Beispiel:",
        sw: "Mfano:",
        mr: "उदाहरण:",
      }),
      exampleNote: t({
        en: "(JLPT N4 Grammar playlist)",
        zh: "(JLPT N4 语法播放列表)",
        ja: "(JLPT N4 文法プレイリスト)",
        ko: "(JLPT N4 문법 재생목록)",
        hi: "(JLPT N4 व्याकरण प्लेलिस्ट)",
        es: "(Lista de gramática JLPT N4)",
        fr: "(Liste de grammaire JLPT N4)",
        ar: "(قائمة تشغيل قواعد JLPT N4)",
        bn: "(JLPT N4 ব্যাকরণ প্লেলিস্ট)",
        pt: "(Playlist de gramática JLPT N4)",
        ru: "(Плейлист грамматики JLPT N4)",
        ur: "(JLPT N4 گرامر پلے لسٹ)",
        id: "(Playlist tata bahasa JLPT N4)",
        de: "(JLPT N4 Grammatik-Playlist)",
        sw: "(Orodha ya sarufi ya JLPT N4)",
        mr: "(JLPT N4 व्याकरण प्लेलिस्ट)",
      }),
      importing: t({
        en: "Importing...",
        zh: "导入中...",
        ja: "インポート中...",
        ko: "가져오는 중...",
        hi: "आयात हो रहा है...",
        es: "Importando...",
        fr: "Importation en cours...",
        ar: "جاري الاستيراد...",
        bn: "আমদানি হচ্ছে...",
        pt: "Importando...",
        ru: "Импорт...",
        ur: "درآمد ہو رہی ہے...",
        id: "Mengimpor...",
        de: "Importiere...",
        sw: "Inaboresha...",
        mr: "आयात करत आहे...",
      }),
      importButton: t({
        en: "Import Playlist",
        zh: "导入播放列表",
        ja: "プレイリストをインポート",
        ko: "재생목록 가져오기",
        hi: "प्लेलिस्ट आयात करें",
        es: "Importar Lista",
        fr: "Importer la Liste",
        ar: "استيراد القائمة",
        bn: "প্লেলিস্ট আমদানি করুন",
        pt: "Importar Playlist",
        ru: "Импортировать Плейлист",
        ur: "پلے لسٹ درآمد کریں",
        id: "Impor Playlist",
        de: "Playlist Importieren",
        sw: "Leta Orodha",
        mr: "प्लेलिस्ट आयात करा",
      }),
    },
    errors: {
      pleaseEnterUrl: t({
        en: "Please enter a URL",
        zh: "请输入 URL",
        ja: "URL を入力してください",
        ko: "URL을 입력하세요",
        hi: "कृपया एक URL दर्ज करें",
        es: "Por favor ingresa una URL",
        fr: "Veuillez entrer une URL",
        ar: "الرجاء إدخال عنوان URL",
        bn: "অনুগ্রহ করে একটি URL লিখুন",
        pt: "Por favor insira uma URL",
        ru: "Пожалуйста, введите URL",
        ur: "براہ کرم ایک URL درج کریں",
        id: "Harap masukkan URL",
        de: "Bitte geben Sie eine URL ein",
        sw: "Tafadhali ingiza URL",
        mr: "कृपया URL प्रविष्ट करा",
      }),
      failedToFetchUrlList: t({
        en: "Failed to fetch URL list",
        zh: "无法获取 URL 列表",
        ja: "URL リストの取得に失敗しました",
        ko: "URL 목록을 가져오지 못했습니다",
        hi: "URL सूची प्राप्त करने में विफल",
        es: "Error al obtener la lista de URLs",
        fr: "Échec de la récupération de la liste d'URLs",
        ar: "فشل في جلب قائمة URL",
        bn: "URL তালিকা আনতে ব্যর্থ",
        pt: "Falha ao buscar lista de URLs",
        ru: "Не удалось получить список URL",
        ur: "URL فہرست حاصل کرنے میں ناکام",
        id: "Gagal mengambil daftar URL",
        de: "Fehler beim Abrufen der URL-Liste",
        sw: "Imeshindwa kupata orodha ya URL",
        mr: "URL यादी मिळवण्यात अयशस्वी",
      }),
      noValidUrlsFound: t({
        en: "No valid URLs found in the file",
        zh: "文件中未找到有效的 URL",
        ja: "ファイル内に有効な URL が見つかりませんでした",
        ko: "파일에서 유효한 URL을 찾을 수 없습니다",
        hi: "फ़ाइल में कोई मान्य URL नहीं मिला",
        es: "No se encontraron URLs válidas en el archivo",
        fr: "Aucune URL valide trouvée dans le fichier",
        ar: "لم يتم العثور على عناوين URL صالحة في الملف",
        bn: "ফাইলে কোনও বৈধ URL পাওয়া যায়নি",
        pt: "Nenhuma URL válida encontrada no arquivo",
        ru: "В файле не найдено действительных URL",
        ur: "فائل میں کوئی درست URL نہیں ملا",
        id: "Tidak ada URL yang valid ditemukan dalam file",
        de: "Keine gültigen URLs in der Datei gefunden",
        sw: "Hakuna URL halali zilizopatikana kwenye faili",
        mr: "फाइलमध्ये कोणतीही वैध URL आढळली नाही",
      }),
      failedToImportFromUrl: t({
        en: "Failed to import from URL",
        zh: "从 URL 导入失败",
        ja: "URL からのインポートに失敗しました",
        ko: "URL에서 가져오기 실패",
        hi: "URL से आयात करने में विफल",
        es: "Error al importar desde URL",
        fr: "Échec de l'importation depuis l'URL",
        ar: "فشل الاستيراد من URL",
        bn: "URL থেকে আমদানি করতে ব্যর্থ",
        pt: "Falha ao importar da URL",
        ru: "Не удалось импортировать из URL",
        ur: "URL سے درآمد کرنے میں ناکام",
        id: "Gagal mengimpor dari URL",
        de: "Fehler beim Importieren von URL",
        sw: "Imeshindwa kuleta kutoka URL",
        mr: "URL वरून आयात करण्यात अयशस्वी",
      }),
      pleaseEnterYoutubeUrl: t({
        en: "Please enter a YouTube playlist URL",
        zh: "请输入 YouTube 播放列表 URL",
        ja: "YouTube プレイリストの URL を入力してください",
        ko: "YouTube 재생목록 URL을 입력하세요",
        hi: "कृपया YouTube प्लेलिस्ट URL दर्ज करें",
        es: "Por favor ingresa una URL de lista de reproducción de YouTube",
        fr: "Veuillez entrer une URL de liste de lecture YouTube",
        ar: "الرجاء إدخال عنوان URL لقائمة تشغيل YouTube",
        bn: "অনুগ্রহ করে YouTube প্লেলিস্ট URL লিখুন",
        pt: "Por favor insira uma URL de playlist do YouTube",
        ru: "Пожалуйста, введите URL плейлиста YouTube",
        ur: "براہ کرم YouTube پلے لسٹ کا URL درج کریں",
        id: "Harap masukkan URL playlist YouTube",
        de: "Bitte geben Sie eine YouTube-Playlist-URL ein",
        sw: "Tafadhali ingiza URL ya orodha ya kucheza ya YouTube",
        mr: "कृपया YouTube प्लेलिस्ट URL प्रविष्ट करा",
      }),
      invalidYoutubeUrl: t({
        en: "Invalid YouTube playlist URL",
        zh: "无效的 YouTube 播放列表 URL",
        ja: "無効な YouTube プレイリスト URL",
        ko: "잘못된 YouTube 재생목록 URL",
        hi: "अमान्य YouTube प्लेलिस्ट URL",
        es: "URL de lista de reproducción de YouTube no válida",
        fr: "URL de liste de lecture YouTube invalide",
        ar: "عنوان URL لقائمة تشغيل YouTube غير صالح",
        bn: "অবৈধ YouTube প্লেলিস্ট URL",
        pt: "URL de playlist do YouTube inválida",
        ru: "Недействительный URL плейлиста YouTube",
        ur: "غلط YouTube پلے لسٹ URL",
        id: "URL playlist YouTube tidak valid",
        de: "Ungültige YouTube-Playlist-URL",
        sw: "URL ya orodha ya kucheza ya YouTube si halali",
        mr: "अवैध YouTube प्लेलिस्ट URL",
      }),
      failedToImportYoutubePlaylist: t({
        en: "Failed to import YouTube playlist",
        zh: "导入 YouTube 播放列表失败",
        ja: "YouTube プレイリストのインポートに失敗しました",
        ko: "YouTube 재생목록 가져오기 실패",
        hi: "YouTube प्लेलिस्ट आयात करने में विफल",
        es: "Error al importar lista de reproducción de YouTube",
        fr: "Échec de l'importation de la liste de lecture YouTube",
        ar: "فشل استيراد قائمة تشغيل YouTube",
        bn: "YouTube প্লেলিস্ট আমদানি করতে ব্যর্থ",
        pt: "Falha ao importar playlist do YouTube",
        ru: "Не удалось импортировать плейлист YouTube",
        ur: "YouTube پلے لسٹ درآمد کرنے میں ناکام",
        id: "Gagal mengimpor playlist YouTube",
        de: "Fehler beim Importieren der YouTube-Playlist",
        sw: "Imeshindwa kuleta orodha ya kucheza ya YouTube",
        mr: "YouTube प्लेलिस्ट आयात करण्यात अयशस्वी",
      }),
      failedToImportFromYoutube: t({
        en: "Failed to import from YouTube",
        zh: "从 YouTube 导入失败",
        ja: "YouTube からのインポートに失敗しました",
        ko: "YouTube에서 가져오기 실패",
        hi: "YouTube से आयात करने में विफल",
        es: "Error al importar desde YouTube",
        fr: "Échec de l'importation depuis YouTube",
        ar: "فشل الاستيراد من YouTube",
        bn: "YouTube থেকে আমদানি করতে ব্যর্থ",
        pt: "Falha ao importar do YouTube",
        ru: "Не удалось импортировать из YouTube",
        ur: "YouTube سے درآمد کرنے میں ناکام",
        id: "Gagal mengimpor dari YouTube",
        de: "Fehler beim Importieren von YouTube",
        sw: "Imeshindwa kuleta kutoka YouTube",
        mr: "YouTube वरून आयात करण्यात अयशस्वी",
      }),
      failedToImportUrls: t({
        en: "Failed to import URLs",
        zh: "导入 URL 失败",
        ja: "URL のインポートに失敗しました",
        ko: "URL 가져오기 실패",
        hi: "URL आयात करने में विफल",
        es: "Error al importar URLs",
        fr: "Échec de l'importation des URLs",
        ar: "فشل استيراد URLs",
        bn: "URL আমদানি করতে ব্যর্থ",
        pt: "Falha ao importar URLs",
        ru: "Не удалось импортировать URL",
        ur: "URL درآمد کرنے میں ناکام",
        id: "Gagal mengimpor URL",
        de: "Fehler beim Importieren von URLs",
        sw: "Imeshindwa kuleta URL",
        mr: "URL आयात करण्यात अयशस्वी",
      }),
    },
    success: {
      importedUrls: t({
        en: "Successfully imported {count} URLs",
        zh: "成功导入 {count} 个 URL",
        ja: "{count} 個の URL をインポートしました",
        ko: "{count}개의 URL을 가져왔습니다",
        hi: "{count} URL सफलतापूर्वक आयात किए गए",
        es: "Se importaron exitosamente {count} URLs",
        fr: "{count} URLs importées avec succès",
        ar: "تم استيراد {count} من URLs بنجاح",
        bn: "{count}টি URL সফলভাবে আমদানি করা হয়েছে",
        pt: "{count} URLs importadas com sucesso",
        ru: "Успешно импортировано {count} URL",
        ur: "{count} URL کامیابی سے درآمد کیے گئے",
        id: "Berhasil mengimpor {count} URL",
        de: "{count} URLs erfolgreich importiert",
        sw: "Imefanikiwa kuleta URL {count}",
        mr: "{count} URL यशस्वीरित्या आयात केले",
      }),
      importedVideos: t({
        en: "Successfully imported {count} videos from playlist",
        zh: "成功从播放列表导入 {count} 个视频",
        ja: "プレイリストから {count} 個の動画をインポートしました",
        ko: "재생목록에서 {count}개의 동영상을 가져왔습니다",
        hi: "प्लेलिस्ट से {count} वीडियो सफलतापूर्वक आयात किए गए",
        es: "Se importaron exitosamente {count} videos de la lista",
        fr: "{count} vidéos importées avec succès depuis la liste",
        ar: "تم استيراد {count} من مقاطع الفيديو من القائمة بنجاح",
        bn: "প্লেলিস্ট থেকে {count}টি ভিডিও সফলভাবে আমদানি করা হয়েছে",
        pt: "{count} vídeos importados com sucesso da playlist",
        ru: "Успешно импортировано {count} видео из плейлиста",
        ur: "پلے لسٹ سے {count} ویڈیوز کامیابی سے درآمد کی گئیں",
        id: "Berhasil mengimpor {count} video dari playlist",
        de: "{count} Videos erfolgreich aus Playlist importiert",
        sw: "Imefanikiwa kuleta video {count} kutoka orodha",
        mr: "प्लेलिस्टमधून {count} व्हिडिओ यशस्वीरित्या आयात केले",
      }),
    },
  },
} satisfies DeclarationContent;

export default learnPageContent;
