services:
  lianki:
    # image: oven/bun # not compatiable with nextjs Edge VM
    image: node
    command: npx -y bun dev --turbo
    environment:
      - PORT=80
      - HOSTNAME=0.0.0.0
    working_dir: /app
    volumes:
      - ./:/app
      - ./.next-srv:/app/.next
    restart: always