import { t, type DeclarationContent } from "intlayer";

/**
 * Labels for the app-shell sidebar. Only what `landing-page.nav` does not
 * already carry lives here — the shell merges the two bags. (The account
 * entries are new: `Header` referenced `nav.signIn` / `nav.dashboard` /
 * `nav.profile` / `nav.preferences` / `nav.membership` / `nav.signOut`, none of
 * which were ever declared, so those links rendered with empty labels.)
 */
const appShellContent = {
  key: "app-shell",
  content: {
    nav: {
      review: t({
        en: "Review",
        zh: "复习",
        hi: "समीक्षा",
        es: "Repasar",
        fr: "Réviser",
        ar: "مراجعة",
        bn: "পুনরালোচনা",
        pt: "Revisar",
        ru: "Повторение",
        ur: "دہرائیں",
        id: "Ulasan",
        de: "Wiederholen",
        ja: "復習",
        sw: "Kagua",
        mr: "उजळणी",
        ko: "복습",
      }),
      cards: t({
        en: "Cards",
        zh: "卡片",
        hi: "कार्ड",
        es: "Tarjetas",
        fr: "Cartes",
        ar: "البطاقات",
        bn: "কার্ড",
        pt: "Cartões",
        ru: "Карточки",
        ur: "کارڈز",
        id: "Kartu",
        de: "Karten",
        ja: "カード",
        sw: "Kadi",
        mr: "कार्ड",
        ko: "카드",
      }),
      selfIntro: t({
        en: "Self Intro",
        zh: "自我介绍",
        hi: "स्व-परिचय",
        es: "Presentación",
        fr: "Présentation",
        ar: "التعريف بالنفس",
        bn: "আত্মপরিচয়",
        pt: "Apresentação",
        ru: "О себе",
        ur: "خود تعارف",
        id: "Perkenalan",
        de: "Vorstellung",
        ja: "自己紹介",
        sw: "Kujitambulisha",
        mr: "स्वओळख",
        ko: "자기소개",
      }),
      read: t({
        en: "Read",
        zh: "阅读",
        hi: "पढ़ें",
        es: "Leer",
        fr: "Lire",
        ar: "قراءة",
        bn: "পড়ুন",
        pt: "Ler",
        ru: "Чтение",
        ur: "پڑھیں",
        id: "Baca",
        de: "Lesen",
        ja: "読む",
        sw: "Soma",
        mr: "वाचा",
        ko: "읽기",
      }),
      addNote: t({
        en: "Add Note",
        zh: "添加笔记",
        hi: "नोट जोड़ें",
        es: "Añadir nota",
        fr: "Ajouter une note",
        ar: "إضافة ملاحظة",
        bn: "নোট যোগ করুন",
        pt: "Adicionar nota",
        ru: "Добавить заметку",
        ur: "نوٹ شامل کریں",
        id: "Tambah Catatan",
        de: "Notiz hinzufügen",
        ja: "ノートを追加",
        sw: "Ongeza Dokezo",
        mr: "टीप जोडा",
        ko: "노트 추가",
      }),
      data: t({
        en: "Data",
        zh: "数据",
        hi: "डेटा",
        es: "Datos",
        fr: "Données",
        ar: "البيانات",
        bn: "ডেটা",
        pt: "Dados",
        ru: "Данные",
        ur: "ڈیٹا",
        id: "Data",
        de: "Daten",
        ja: "データ",
        sw: "Data",
        mr: "डेटा",
        ko: "데이터",
      }),
      signIn: t({
        en: "Sign in",
        zh: "登录",
        hi: "साइन इन",
        es: "Iniciar sesión",
        fr: "Se connecter",
        ar: "تسجيل الدخول",
        bn: "সাইন ইন",
        pt: "Entrar",
        ru: "Войти",
        ur: "سائن ان",
        id: "Masuk",
        de: "Anmelden",
        ja: "ログイン",
        sw: "Ingia",
        mr: "साइन इन",
        ko: "로그인",
      }),
      signOut: t({
        en: "Sign out",
        zh: "退出登录",
        hi: "साइन आउट",
        es: "Cerrar sesión",
        fr: "Se déconnecter",
        ar: "تسجيل الخروج",
        bn: "সাইন আউট",
        pt: "Sair",
        ru: "Выйти",
        ur: "سائن آؤٹ",
        id: "Keluar",
        de: "Abmelden",
        ja: "ログアウト",
        sw: "Toka",
        mr: "साइन आउट",
        ko: "로그아웃",
      }),
      dashboard: t({
        en: "Dashboard",
        zh: "仪表板",
        hi: "डैशबोर्ड",
        es: "Panel",
        fr: "Tableau de bord",
        ar: "لوحة التحكم",
        bn: "ড্যাশবোর্ড",
        pt: "Painel",
        ru: "Панель",
        ur: "ڈیش بورڈ",
        id: "Dasbor",
        de: "Übersicht",
        ja: "ダッシュボード",
        sw: "Dashibodi",
        mr: "डॅशबोर्ड",
        ko: "대시보드",
      }),
      profile: t({
        en: "Profile",
        zh: "个人资料",
        hi: "प्रोफ़ाइल",
        es: "Perfil",
        fr: "Profil",
        ar: "الملف الشخصي",
        bn: "প্রোফাইল",
        pt: "Perfil",
        ru: "Профиль",
        ur: "پروفائل",
        id: "Profil",
        de: "Profil",
        ja: "プロフィール",
        sw: "Wasifu",
        mr: "प्रोफाइल",
        ko: "프로필",
      }),
      preferences: t({
        en: "Preferences",
        zh: "偏好设置",
        hi: "प्राथमिकताएँ",
        es: "Preferencias",
        fr: "Préférences",
        ar: "التفضيلات",
        bn: "পছন্দসমূহ",
        pt: "Preferências",
        ru: "Настройки",
        ur: "ترجیحات",
        id: "Preferensi",
        de: "Einstellungen",
        ja: "設定",
        sw: "Mapendeleo",
        mr: "प्राधान्ये",
        ko: "환경설정",
      }),
      membership: t({
        en: "Membership",
        zh: "会员",
        hi: "सदस्यता",
        es: "Membresía",
        fr: "Abonnement",
        ar: "العضوية",
        bn: "সদস্যপদ",
        pt: "Assinatura",
        ru: "Подписка",
        ur: "رکنیت",
        id: "Keanggotaan",
        de: "Mitgliedschaft",
        ja: "メンバーシップ",
        sw: "Uanachama",
        mr: "सदस्यत्व",
        ko: "멤버십",
      }),
    },
    groups: {
      main: t({
        en: "Learn",
        zh: "学习",
        hi: "सीखें",
        es: "Aprender",
        fr: "Apprendre",
        ar: "تعلم",
        bn: "শিখুন",
        pt: "Aprender",
        ru: "Учиться",
        ur: "سیکھیں",
        id: "Belajar",
        de: "Lernen",
        ja: "学ぶ",
        sw: "Jifunze",
        mr: "शिका",
        ko: "학습",
      }),
      data: t({
        en: "Data",
        zh: "数据",
        hi: "डेटा",
        es: "Datos",
        fr: "Données",
        ar: "البيانات",
        bn: "ডেটা",
        pt: "Dados",
        ru: "Данные",
        ur: "ڈیٹا",
        id: "Data",
        de: "Daten",
        ja: "データ",
        sw: "Data",
        mr: "डेटा",
        ko: "데이터",
      }),
      account: t({
        en: "Account",
        zh: "账户",
        hi: "खाता",
        es: "Cuenta",
        fr: "Compte",
        ar: "الحساب",
        bn: "অ্যাকাউন্ট",
        pt: "Conta",
        ru: "Аккаунт",
        ur: "اکاؤنٹ",
        id: "Akun",
        de: "Konto",
        ja: "アカウント",
        sw: "Akaunti",
        mr: "खाते",
        ko: "계정",
      }),
    },
    ui: {
      menu: t({
        en: "Menu",
        zh: "菜单",
        hi: "मेन्यू",
        es: "Menú",
        fr: "Menu",
        ar: "القائمة",
        bn: "মেনু",
        pt: "Menu",
        ru: "Меню",
        ur: "مینو",
        id: "Menu",
        de: "Menü",
        ja: "メニュー",
        sw: "Menyu",
        mr: "मेनू",
        ko: "메뉴",
      }),
      collapse: t({
        en: "Collapse sidebar",
        zh: "收起侧边栏",
        hi: "साइडबार छोटा करें",
        es: "Contraer barra lateral",
        fr: "Réduire la barre latérale",
        ar: "طي الشريط الجانبي",
        bn: "সাইডবার সংকুচিত করুন",
        pt: "Recolher barra lateral",
        ru: "Свернуть панель",
        ur: "سائیڈ بار سکیڑیں",
        id: "Ciutkan bilah sisi",
        de: "Seitenleiste einklappen",
        ja: "サイドバーを折りたたむ",
        sw: "Kunja upau wa kando",
        mr: "साइडबार लहान करा",
        ko: "사이드바 접기",
      }),
      expand: t({
        en: "Expand sidebar",
        zh: "展开侧边栏",
        hi: "साइडबार बड़ा करें",
        es: "Expandir barra lateral",
        fr: "Développer la barre latérale",
        ar: "توسيع الشريط الجانبي",
        bn: "সাইডবার প্রসারিত করুন",
        pt: "Expandir barra lateral",
        ru: "Развернуть панель",
        ur: "سائیڈ بار پھیلائیں",
        id: "Perluas bilah sisi",
        de: "Seitenleiste ausklappen",
        ja: "サイドバーを展開",
        sw: "Panua upau wa kando",
        mr: "साइडबार मोठा करा",
        ko: "사이드바 펼치기",
      }),
    },
  },
} satisfies DeclarationContent;

export default appShellContent;
