import { t, type DeclarationContent } from "intlayer";

const profilePageContent = {
  key: "profile-page",
  content: {
    metadata: {
      title: t({
        en: "Profile - Lianki",
        zh: "个人资料 - Lianki",
        ja: "プロフィール - Lianki",
        ko: "프로필 - Lianki",
        hi: "प्रोफाइल - Lianki",
        es: "Perfil - Lianki",
        fr: "Profil - Lianki",
        ar: "الملف الشخصي - Lianki",
        bn: "প্রোফাইল - Lianki",
        pt: "Perfil - Lianki",
        ru: "Профиль - Lianki",
        ur: "پروفائل - Lianki",
        id: "Profil - Lianki",
        de: "Profil - Lianki",
        sw: "Wasifu - Lianki",
        mr: "प्रोफाइल - Lianki",
      }),
      description: t({
        en: "View and manage your Lianki profile",
        zh: "查看和管理您的 Lianki 个人资料",
        ja: "Lianki プロフィールを表示・管理",
        ko: "Lianki 프로필 보기 및 관리",
        hi: "अपनी Lianki प्रोफाइल देखें और प्रबंधित करें",
        es: "Ver y gestionar tu perfil de Lianki",
        fr: "Voir et gérer votre profil Lianki",
        ar: "عرض وإدارة ملفك الشخصي في Lianki",
        bn: "আপনার Lianki প্রোফাইল দেখুন এবং পরিচালনা করুন",
        pt: "Visualizar e gerenciar seu perfil Lianki",
        ru: "Просмотр и управление вашим профилем Lianki",
        ur: "اپنا Lianki پروفائل دیکھیں اور منیج کریں",
        id: "Lihat dan kelola profil Lianki Anda",
        de: "Sehen und verwalten Sie Ihr Lianki-Profil",
        sw: "Tazama na udhibiti wasifu wako wa Lianki",
        mr: "आपले Lianki प्रोफाइल पहा आणि व्यवस्थापित करा",
      }),
    },
    heading: t({
      en: "Profile",
      zh: "个人资料",
      ja: "プロフィール",
      ko: "프로필",
      hi: "प्रोफाइल",
      es: "Perfil",
      fr: "Profil",
      ar: "الملف الشخصي",
      bn: "প্রোফাইল",
      pt: "Perfil",
      ru: "Профиль",
      ur: "پروفائل",
      id: "Profil",
      de: "Profil",
      sw: "Wasifu",
      mr: "प्रोफाइल",
    }),
    userInformation: t({
      en: "User Information",
      zh: "用户信息",
      ja: "ユーザー情報",
      ko: "사용자 정보",
      hi: "उपयोगकर्ता जानकारी",
      es: "Información del Usuario",
      fr: "Informations Utilisateur",
      ar: "معلومات المستخدم",
      bn: "ব্যবহারকারীর তথ্য",
      pt: "Informações do Usuário",
      ru: "Информация о Пользователе",
      ur: "صارف کی معلومات",
      id: "Informasi Pengguna",
      de: "Benutzerinformationen",
      sw: "Maelezo ya Mtumiaji",
      mr: "वापरकर्ता माहिती",
    }),
    name: t({
      en: "Name:",
      zh: "姓名：",
      ja: "名前：",
      ko: "이름:",
      hi: "नाम:",
      es: "Nombre:",
      fr: "Nom:",
      ar: "الاسم:",
      bn: "নাম:",
      pt: "Nome:",
      ru: "Имя:",
      ur: "نام:",
      id: "Nama:",
      de: "Name:",
      sw: "Jina:",
      mr: "नाव:",
    }),
    notAvailable: t({
      en: "N/A",
      zh: "不适用",
      ja: "該当なし",
      ko: "해당 없음",
      hi: "लागू नहीं",
      es: "N/D",
      fr: "N/D",
      ar: "غير متوفر",
      bn: "প্রযোজ্য নয়",
      pt: "N/D",
      ru: "Н/Д",
      ur: "دستیاب نہیں",
      id: "T/A",
      de: "N/V",
      sw: "Haipo",
      mr: "उपलब्ध नाही",
    }),
    email: t({
      en: "Email:",
      zh: "电子邮件：",
      ja: "メール：",
      ko: "이메일:",
      hi: "ईमेल:",
      es: "Correo:",
      fr: "E-mail:",
      ar: "البريد الإلكتروني:",
      bn: "ইমেল:",
      pt: "E-mail:",
      ru: "Эл. почта:",
      ur: "ای میل:",
      id: "Email:",
      de: "E-Mail:",
      sw: "Barua pepe:",
      mr: "ईमेल:",
    }),
    avatar: t({
      en: "Avatar:",
      zh: "头像：",
      ja: "アバター：",
      ko: "아바타:",
      hi: "अवतार:",
      es: "Avatar:",
      fr: "Avatar:",
      ar: "الصورة الرمزية:",
      bn: "অবতার:",
      pt: "Avatar:",
      ru: "Аватар:",
      ur: "تصویر:",
      id: "Avatar:",
      de: "Avatar:",
      sw: "Picha:",
      mr: "अवतार:",
    }),
    userAvatarAlt: t({
      en: "User avatar",
      zh: "用户头像",
      ja: "ユーザーアバター",
      ko: "사용자 아바타",
      hi: "उपयोगकर्ता अवतार",
      es: "Avatar del usuario",
      fr: "Avatar de l'utilisateur",
      ar: "الصورة الرمزية للمستخدم",
      bn: "ব্যবহারকারীর অবতার",
      pt: "Avatar do usuário",
      ru: "Аватар пользователя",
      ur: "صارف کی تصویر",
      id: "Avatar pengguna",
      de: "Benutzer-Avatar",
      sw: "Picha ya mtumiaji",
      mr: "वापरकर्ता अवतार",
    }),
    sessionDetails: t({
      en: "Session Details",
      zh: "会话详情",
      ja: "セッション詳細",
      ko: "세션 세부정보",
      hi: "सत्र विवरण",
      es: "Detalles de Sesión",
      fr: "Détails de Session",
      ar: "تفاصيل الجلسة",
      bn: "সেশনের বিবরণ",
      pt: "Detalhes da Sessão",
      ru: "Детали Сессии",
      ur: "سیشن کی تفصیلات",
      id: "Detail Sesi",
      de: "Sitzungsdetails",
      sw: "Maelezo ya Kikao",
      mr: "सत्र तपशील",
    }),
    editPreferences: t({
      en: "Edit Preferences",
      zh: "编辑偏好设置",
      ja: "設定を編集",
      ko: "환경설정 편집",
      hi: "प्राथमिकताएँ संपादित करें",
      es: "Editar Preferencias",
      fr: "Modifier les Préférences",
      ar: "تعديل التفضيلات",
      bn: "পছন্দসমূহ সম্পাদনা করুন",
      pt: "Editar Preferências",
      ru: "Редактировать Настройки",
      ur: "ترجیحات میں ترمیم کریں",
      id: "Edit Preferensi",
      de: "Einstellungen Bearbeiten",
      sw: "Hariri Mapendeleo",
      mr: "प्राधान्ये संपादित करा",
    }),
    backToHome: t({
      en: "Back to Home",
      zh: "返回主页",
      ja: "ホームに戻る",
      ko: "홈으로 돌아가기",
      hi: "होम पर वापस जाएं",
      es: "Volver al Inicio",
      fr: "Retour à l'Accueil",
      ar: "العودة إلى الصفحة الرئيسية",
      bn: "হোমে ফিরে যান",
      pt: "Voltar ao Início",
      ru: "Вернуться на Главную",
      ur: "ہوم پر واپس جائیں",
      id: "Kembali ke Beranda",
      de: "Zurück zur Startseite",
      sw: "Rudi Nyumbani",
      mr: "होमवर परत जा",
    }),
  },
} satisfies DeclarationContent;

export default profilePageContent;
