import { readFileSync } from "fs";
import { join } from "path";
import { describe, expect, it } from "bun:test";
import { LIANKI_USERSCRIPT_VERSION } from "@/lib/userscript-version";

/**
 * The runtime constant is generated by scripts/pre-commit.ts. It exists because the
 * Workers runtime has no filesystem: reading public/lianki.meta.js at request time
 * returned "0.0.0", so the install button never reported an update as available.
 * Nothing at runtime can detect drift anymore, so pin it here instead.
 */
describe("LIANKI_USERSCRIPT_VERSION", () => {
  const versionIn = (file: string): string => {
    const found = readFileSync(join(process.cwd(), file), "utf8").match(/@version\s+(\S+)/)?.[1];
    // Throw rather than return undefined: a file that lost its @version header
    // should fail this guard outright, not compare equal to nothing.
    if (!found) throw new Error(`no @version header found in ${file}`);
    return found;
  };

  it("matches the shipped userscript", () => {
    expect(LIANKI_USERSCRIPT_VERSION).toBe(versionIn("public/lianki.user.js"));
  });

  it("matches the metadata file used for update checks", () => {
    expect(LIANKI_USERSCRIPT_VERSION).toBe(versionIn("public/lianki.meta.js"));
  });

  it("is never the fallback that the filesystem read used to produce", () => {
    expect(LIANKI_USERSCRIPT_VERSION).not.toBe("0.0.0");
    expect(LIANKI_USERSCRIPT_VERSION).toMatch(/^\d+\.\d+\.\d+$/);
  });
});
