import { t, type DeclarationContent } from "intlayer";

const contactFormContent = {
  key: "contact-form",
  content: {
    title: t({
      en: "Contact Us",
      zh: "联系我们",
      ja: "お問い合わせ",
      ko: "문의하기",
      hi: "संपर्क करें",
      es: "Contáctanos",
      fr: "Contactez-nous",
      ar: "اتصل بنا",
      bn: "যোগাযোগ করুন",
      pt: "Contacte-nos",
      ru: "Свяжитесь с нами",
      ur: "رابطہ کریں",
      id: "Hubungi Kami",
      de: "Kontaktieren Sie uns",
      sw: "Wasiliana Nasi",
      mr: "आमच्याशी संपर्क करा",
    }),

    nameLabel: t({
      en: "Name",
      zh: "姓名",
      ja: "名前",
      ko: "이름",
      hi: "नाम",
      es: "Nombre",
      fr: "Nom",
      ar: "الاسم",
      bn: "নাম",
      pt: "Nome",
      ru: "Имя",
      ur: "نام",
      id: "Nama",
      de: "Name",
      sw: "Jina",
      mr: "नाव",
    }),

    namePlaceholder: t({
      en: "Your name",
      zh: "您的姓名",
      ja: "お名前",
      ko: "이름을 입력하세요",
      hi: "आपका नाम",
      es: "Tu nombre",
      fr: "Votre nom",
      ar: "اسمك",
      bn: "আপনার নাম",
      pt: "O seu nome",
      ru: "Ваше имя",
      ur: "آپ کا نام",
      id: "Nama Anda",
      de: "Ihr Name",
      sw: "Jina lako",
      mr: "तुमचे नाव",
    }),

    emailLabel: t({
      en: "Email",
      zh: "邮箱",
      ja: "メール",
      ko: "이메일",
      hi: "ईमेल",
      es: "Correo electrónico",
      fr: "E-mail",
      ar: "البريد الإلكتروني",
      bn: "ইমেইল",
      pt: "E-mail",
      ru: "Электронная почта",
      ur: "ای میل",
      id: "Email",
      de: "E-Mail",
      sw: "Barua pepe",
      mr: "ईमेल",
    }),

    emailPlaceholder: t({
      en: "you@example.com",
      zh: "您的邮箱@example.com",
      ja: "you@example.com",
      ko: "you@example.com",
      hi: "you@example.com",
      es: "tu@ejemplo.com",
      fr: "vous@exemple.com",
      ar: "you@example.com",
      bn: "you@example.com",
      pt: "voce@exemplo.com",
      ru: "you@example.com",
      ur: "you@example.com",
      id: "anda@contoh.com",
      de: "sie@beispiel.com",
      sw: "you@example.com",
      mr: "you@example.com",
    }),

    phoneLabel: t({
      en: "Phone",
      zh: "电话",
      ja: "電話",
      ko: "전화",
      hi: "फ़ोन",
      es: "Teléfono",
      fr: "Téléphone",
      ar: "الهاتف",
      bn: "ফোন",
      pt: "Telefone",
      ru: "Телефон",
      ur: "فون",
      id: "Telepon",
      de: "Telefon",
      sw: "Simu",
      mr: "फोन",
    }),

    phonePlaceholder: t({
      en: "+1 234 567 8900",
      zh: "+86 123 4567 8900",
      ja: "+81 12 3456 7890",
      ko: "+82 10 1234 5678",
      hi: "+91 1234567890",
      es: "+34 123 456 789",
      fr: "+33 1 23 45 67 89",
      ar: "+966 12 345 6789",
      bn: "+880 1234 567890",
      pt: "+351 123 456 789",
      ru: "+7 123 456 7890",
      ur: "+92 123 4567890",
      id: "+62 812 3456 7890",
      de: "+49 123 4567890",
      sw: "+255 123 456 789",
      mr: "+91 1234567890",
    }),

    messageLabel: t({
      en: "Message",
      zh: "留言",
      ja: "メッセージ",
      ko: "메시지",
      hi: "संदेश",
      es: "Mensaje",
      fr: "Message",
      ar: "الرسالة",
      bn: "বার্তা",
      pt: "Mensagem",
      ru: "Сообщение",
      ur: "پیغام",
      id: "Pesan",
      de: "Nachricht",
      sw: "Ujumbe",
      mr: "संदेश",
    }),

    messagePlaceholder: t({
      en: "Tell us what you'd like to learn...",
      zh: "告诉我们您想学什么...",
      ja: "学びたいことを教えてください...",
      ko: "배우고 싶은 것을 알려주세요...",
      hi: "हमें बताएं कि आप क्या सीखना चाहते हैं...",
      es: "Cuéntanos qué te gustaría aprender...",
      fr: "Dites-nous ce que vous aimeriez apprendre...",
      ar: "أخبرنا بما تود تعلمه...",
      bn: "আপনি কী শিখতে চান তা আমাদের বলুন...",
      pt: "Diga-nos o que gostaria de aprender...",
      ru: "Расскажите, что вы хотели бы изучить...",
      ur: "ہمیں بتائیں کہ آپ کیا سیکھنا چاہتے ہیں...",
      id: "Beri tahu kami apa yang ingin Anda pelajari...",
      de: "Sagen Sie uns, was Sie lernen möchten...",
      sw: "Tuambie unachopenda kujifunza...",
      mr: "तुम्हाला काय शिकायचे आहे ते सांगा...",
    }),

    optional: t({
      en: "(optional)",
      zh: "（可选）",
      ja: "（任意）",
      ko: "(선택사항)",
      hi: "(वैकल्पिक)",
      es: "(opcional)",
      fr: "(facultatif)",
      ar: "(اختياري)",
      bn: "(ঐচ্ছিক)",
      pt: "(opcional)",
      ru: "(необязательно)",
      ur: "(اختیاری)",
      id: "(opsional)",
      de: "(optional)",
      sw: "(si lazima)",
      mr: "(पर्यायी)",
    }),

    template1: t({
      en: "I want to learn a language faster",
      zh: "我想更快地学习语言",
      ja: "言語をより早く学びたい",
      ko: "언어를 더 빨리 배우고 싶어요",
      hi: "मैं एक भाषा तेजी से सीखना चाहता हूं",
      es: "Quiero aprender un idioma más rápido",
      fr: "Je veux apprendre une langue plus rapidement",
      ar: "أريد تعلم لغة بشكل أسرع",
      bn: "আমি দ্রুত একটি ভাষা শিখতে চাই",
      pt: "Quero aprender um idioma mais rapidamente",
      ru: "Я хочу быстрее выучить язык",
      ur: "میں زبان تیزی سے سیکھنا چاہتا ہوں",
      id: "Saya ingin belajar bahasa lebih cepat",
      de: "Ich möchte eine Sprache schneller lernen",
      sw: "Nataka kujifunza lugha haraka zaidi",
      mr: "मला भाषा जलद शिकायची आहे",
    }),

    template2: t({
      en: "I want to learn an instrument faster",
      zh: "我想更快地学习乐器",
      ja: "楽器をより早く学びたい",
      ko: "악기를 더 빨리 배우고 싶어요",
      hi: "मैं एक वाद्य यंत्र तेजी से सीखना चाहता हूं",
      es: "Quiero aprender un instrumento más rápido",
      fr: "Je veux apprendre un instrument plus rapidement",
      ar: "أريد تعلم آلة موسيقية بشكل أسرع",
      bn: "আমি দ্রুত একটি যন্ত্র শিখতে চাই",
      pt: "Quero aprender um instrumento mais rapidamente",
      ru: "Я хочу быстрее освоить музыкальный инструмент",
      ur: "میں آلہ موسیقی تیزی سے سیکھنا چاہتا ہوں",
      id: "Saya ingin belajar instrumen lebih cepat",
      de: "Ich möchte ein Instrument schneller lernen",
      sw: "Nataka kujifunza chombo cha muziki haraka zaidi",
      mr: "मला वाद्य जलद शिकायचे आहे",
    }),

    template3: t({
      en: "I want to learn skills faster",
      zh: "我想更快地学习技能",
      ja: "スキルをより早く学びたい",
      ko: "기술을 더 빨리 배우고 싶어요",
      hi: "मैं कौशल तेजी से सीखना चाहता हूं",
      es: "Quiero aprender habilidades más rápido",
      fr: "Je veux apprendre des compétences plus rapidement",
      ar: "أريد تعلم مهارات بشكل أسرع",
      bn: "আমি দ্রুত দক্ষতা শিখতে চাই",
      pt: "Quero aprender habilidades mais rapidamente",
      ru: "Я хочу быстрее освоить навыки",
      ur: "میں مہارتیں تیزی سے سیکھنا چاہتا ہوں",
      id: "Saya ingin belajar keterampilan lebih cepat",
      de: "Ich möchte Fähigkeiten schneller lernen",
      sw: "Nataka kujifunza ujuzi haraka zaidi",
      mr: "मला कौशल्ये जलद शिकायची आहेत",
    }),

    sendButton: t({
      en: "Send Message",
      zh: "发送消息",
      ja: "メッセージを送信",
      ko: "메시지 보내기",
      hi: "संदेश भेजें",
      es: "Enviar mensaje",
      fr: "Envoyer le message",
      ar: "إرسال رسالة",
      bn: "বার্তা পাঠান",
      pt: "Enviar mensagem",
      ru: "Отправить сообщение",
      ur: "پیغام بھیجیں",
      id: "Kirim Pesan",
      de: "Nachricht senden",
      sw: "Tuma Ujumbe",
      mr: "संदेश पाठवा",
    }),

    sending: t({
      en: "Sending...",
      zh: "发送中...",
      ja: "送信中...",
      ko: "전송 중...",
      hi: "भेजा जा रहा है...",
      es: "Enviando...",
      fr: "Envoi en cours...",
      ar: "جاري الإرسال...",
      bn: "পাঠানো হচ্ছে...",
      pt: "Enviando...",
      ru: "Отправка...",
      ur: "بھیجا جا رہا ہے...",
      id: "Mengirim...",
      de: "Wird gesendet...",
      sw: "Inatuma...",
      mr: "पाठवत आहे...",
    }),

    successMessage: t({
      en: "Message sent! We'll get back to you soon.",
      zh: "消息已发送！我们会尽快回复您。",
      ja: "メッセージを送信しました！すぐに返信いたします。",
      ko: "메시지가 전송되었습니다! 곧 연락드리겠습니다.",
      hi: "संदेश भेजा गया! हम जल्द ही आपसे संपर्क करेंगे।",
      es: "¡Mensaje enviado! Te responderemos pronto.",
      fr: "Message envoyé ! Nous vous répondrons bientôt.",
      ar: "تم إرسال الرسالة! سنعود إليك قريبًا.",
      bn: "বার্তা পাঠানো হয়েছে! আমরা শীघ্রই আপনার সাথে যোগাযোগ করব।",
      pt: "Mensagem enviada! Entraremos em contato em breve.",
      ru: "Сообщение отправлено! Мы скоро свяжемся с вами.",
      ur: "پیغام بھیج دیا گیا! ہم جلد ہی آپ سے رابطہ کریں گے۔",
      id: "Pesan terkirim! Kami akan segera menghubungi Anda.",
      de: "Nachricht gesendet! Wir melden uns bald bei Ihnen.",
      sw: "Ujumbe umetumwa! Tutawasiliana nawe hivi karibuni.",
      mr: "संदेश पाठवला! आम्ही लवकरच तुमच्याशी संपर्क करू.",
    }),

    errorMessage: t({
      en: "Something went wrong. Please try again.",
      zh: "出错了。请重试。",
      ja: "問題が発生しました。もう一度お試しください。",
      ko: "문제가 발생했습니다. 다시 시도해 주세요.",
      hi: "कुछ गलत हो गया। कृपया पुनः प्रयास करें।",
      es: "Algo salió mal. Por favor, inténtalo de nuevo.",
      fr: "Une erreur s'est produite. Veuillez réessayer.",
      ar: "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
      bn: "কিছু ভুল হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
      pt: "Algo correu mal. Por favor, tente novamente.",
      ru: "Что-то пошло не так. Пожалуйста, попробуйте еще раз.",
      ur: "کچھ غلط ہو گیا۔ براہ کرم دوبارہ کوشش کریں۔",
      id: "Terjadi kesalahan. Silakan coba lagi.",
      de: "Etwas ist schief gelaufen. Bitte versuchen Sie es erneut.",
      sw: "Kuna kitu kimeenda vibaya. Tafadhali jaribu tena.",
      mr: "काहीतरी चूक झाली. कृपया पुन्हा प्रयत्न करा.",
    }),
  },
} satisfies DeclarationContent;

export default contactFormContent;
