import { t, type DeclarationContent } from "intlayer";

const membershipContent = {
  key: "membership-page",
  content: {
    backToHome: t({
      en: "← Back to Home",
      zh: "← 返回首页",
      ja: "← ホームに戻る",
      ko: "← 홈으로 돌아가기",
      hi: "← होम पर वापस जाएं",
      es: "← Volver al inicio",
      fr: "← Retour à l'accueil",
      ar: "← العودة إلى الرئيسية",
      bn: "← হোমে ফিরুন",
      pt: "← Voltar ao início",
      ru: "← На главную",
      ur: "← گھر واپس",
      id: "← Kembali ke beranda",
      de: "← Zurück zur Startseite",
      sw: "← Rudi nyumbani",
      mr: "← मुख्यपृष्ठावर परत",
    }),
    title: t({
      en: "Membership",
      zh: "会员",
      ja: "メンバーシップ",
      ko: "멤버십",
      hi: "सदस्यता",
      es: "Membresía",
      fr: "Abonnement",
      ar: "العضوية",
      bn: "সদস্যপদ",
      pt: "Assinatura",
      ru: "Подписка",
      ur: "رکنیت",
      id: "Keanggotaan",
      de: "Mitgliedschaft",
      sw: "Uanachama",
      mr: "सदस्यत्व",
    }),
    loading: t({
      en: "Loading...",
      zh: "加载中...",
      ja: "読み込み中...",
      ko: "로딩 중...",
      hi: "लोड हो रहा है...",
      es: "Cargando...",
      fr: "Chargement...",
      ar: "جارٍ التحميل...",
      bn: "লোড হচ্ছে...",
      pt: "Carregando...",
      ru: "Загрузка...",
      ur: "لوڈ ہو رہا ہے...",
      id: "Memuat...",
      de: "Lädt...",
      sw: "Inapakia...",
      mr: "लोड होत आहे...",
    }),
    error: {
      failedToLoad: t({
        en: "Failed to load membership information.",
        zh: "无法加载会员信息。",
        ja: "会員情報の読み込みに失敗しました。",
        ko: "멤버십 정보를 불러오지 못했습니다.",
        hi: "सदस्यता जानकारी लोड करने में विफल।",
        es: "Error al cargar la información de membresía.",
        fr: "Impossible de charger les informations d'abonnement.",
        ar: "فشل تحميل معلومات العضوية.",
        bn: "সদস্যপদ তথ্য লোড করতে ব্যর্থ হয়েছে।",
        pt: "Falha ao carregar informações de assinatura.",
        ru: "Не удалось загрузить информацию о подписке.",
        ur: "رکنیت کی معلومات لوڈ کرنے میں ناکامی۔",
        id: "Gagal memuat informasi keanggotaan.",
        de: "Mitgliedschaftsinformationen konnten nicht geladen werden.",
        sw: "Imeshindwa kupakia maelezo ya uanachama.",
        mr: "सदस्यत्व माहिती लोड करण्यात अयशस्वी.",
      }),
    },
    newUserBenefit: {
      title: t({
        en: "90-Day Free Trial for New Users",
        zh: "新用户免费试用90天",
        ja: "新規ユーザー向け90日間無料トライアル",
        ko: "신규 사용자를 위한 90일 무료 체험",
        hi: "नए उपयोगकर्ताओं के लिए 90 दिन का निःशुल्क परीक्षण",
        es: "Prueba gratuita de 90 días para nuevos usuarios",
        fr: "Essai gratuit de 90 jours pour les nouveaux utilisateurs",
        ar: "تجربة مجانية لمدة 90 يومًا للمستخدمين الجدد",
        bn: "নতুন ব্যবহারকারীদের জন্য ৯০ দিনের বিনামূল্যে ট্রায়াল",
        pt: "Teste gratuito de 90 dias para novos usuários",
        ru: "90-дневный бесплатный пробный период для новых пользователей",
        ur: "نئے صارفین کے لیے 90 دن کا مفت ٹرائل",
        id: "Uji coba gratis 90 hari untuk pengguna baru",
        de: "90-tägige kostenlose Testversion für neue Benutzer",
        sw: "Jaribio la bure la siku 90 kwa watumiaji wapya",
        mr: "नवीन वापरकर्त्यांसाठी 90 दिवसांची विनामूल्य चाचणी",
      }),
      description: t({
        en: "All new accounts automatically receive a 90-day Pro trial. Enjoy all Pro features at no cost.",
        zh: "所有新账户自动获得90天专业版试用。免费享受所有专业功能。",
        ja: "すべての新規アカウントには自動的に90日間のProトライアルが付与されます。すべてのPro機能を無料でお楽しみください。",
        ko: "모든 신규 계정은 자동으로 90일 Pro 체험을 받습니다. 모든 Pro 기능을 무료로 즐기세요.",
        hi: "सभी नए खाते स्वचालित रूप से 90-दिन का Pro ट्रायल प्राप्त करते हैं। सभी Pro सुविधाएं निःशुल्क उपयोग करें।",
        es: "Todas las cuentas nuevas reciben automáticamente una prueba Pro de 90 días. Disfruta de todas las funciones Pro sin costo.",
        fr: "Tous les nouveaux comptes reçoivent automatiquement un essai Pro de 90 jours. Profitez de toutes les fonctionnalités Pro gratuitement.",
        ar: "تتلقى جميع الحسابات الجديدة تلقائيًا تجربة Pro لمدة 90 يومًا. استمتع بجميع ميزات Pro مجانًا.",
        bn: "সমস্ত নতুন অ্যাকাউন্ট স্বয়ংক্রিয়ভাবে ৯০ দিনের Pro ট্রায়াল পায়। সমস্ত Pro বৈশিষ্ট্য বিনামূল্যে উপভোগ করুন।",
        pt: "Todas as novas contas recebem automaticamente um teste Pro de 90 dias. Aproveite todos os recursos Pro sem custo.",
        ru: "Все новые аккаунты автоматически получают 90-дневный пробный период Pro. Наслаждайтесь всеми функциями Pro бесплатно.",
        ur: "تمام نئے اکاؤنٹس کو خودکار طور پر 90 دن کا Pro ٹرائل ملتا ہے۔ تمام Pro خصوصیات مفت میں لطف اٹھائیں۔",
        id: "Semua akun baru secara otomatis menerima uji coba Pro 90 hari. Nikmati semua fitur Pro tanpa biaya.",
        de: "Alle neuen Konten erhalten automatisch eine 90-tägige Pro-Testversion. Genießen Sie alle Pro-Funktionen kostenlos.",
        sw: "Akaunti zote mpya hupokea jaribio la Pro la siku 90 kiotomatiki. Furahia vipengele vyote vya Pro bila gharama.",
        mr: "सर्व नवीन खाती आपोआप 90-दिवसांचा Pro ट्रायल प्राप्त करतात. सर्व Pro वैशिष्ट्ये विनामूल्य उपभोगा.",
      }),
    },
    currentStatus: {
      title: t({
        en: "Your Current Plan",
        zh: "您当前的计划",
        ja: "現在のプラン",
        ko: "현재 플랜",
        hi: "आपकी वर्तमान योजना",
        es: "Tu plan actual",
        fr: "Votre plan actuel",
        ar: "خطتك الحالية",
        bn: "আপনার বর্তমান পরিকল্পনা",
        pt: "Seu plano atual",
        ru: "Ваш текущий план",
        ur: "آپ کا موجودہ پلان",
        id: "Paket Anda saat ini",
        de: "Ihr aktueller Plan",
        sw: "Mpango wako wa sasa",
        mr: "तुमची सध्याची योजना",
      }),
      free: t({
        en: "Free",
        zh: "免费版",
        ja: "フリー",
        ko: "무료",
        hi: "निःशुल्क",
        es: "Gratis",
        fr: "Gratuit",
        ar: "مجاني",
        bn: "বিনামূল্যে",
        pt: "Grátis",
        ru: "Бесплатно",
        ur: "مفت",
        id: "Gratis",
        de: "Kostenlos",
        sw: "Bila malipo",
        mr: "विनामूल्य",
      }),
      trial: t({
        en: "Pro Trial",
        zh: "专业版试用",
        ja: "Pro トライアル",
        ko: "Pro 체험",
        hi: "Pro ट्रायल",
        es: "Prueba Pro",
        fr: "Essai Pro",
        ar: "تجربة Pro",
        bn: "Pro ট্রায়াল",
        pt: "Teste Pro",
        ru: "Пробный Pro",
        ur: "Pro ٹرائل",
        id: "Uji Coba Pro",
        de: "Pro-Test",
        sw: "Jaribio la Pro",
        mr: "Pro ट्रायल",
      }),
      pro: t({
        en: "Pro",
        zh: "专业版",
        ja: "Pro",
        ko: "Pro",
        hi: "Pro",
        es: "Pro",
        fr: "Pro",
        ar: "Pro",
        bn: "Pro",
        pt: "Pro",
        ru: "Pro",
        ur: "Pro",
        id: "Pro",
        de: "Pro",
        sw: "Pro",
        mr: "Pro",
      }),
      trialExpires: t({
        en: "Trial expires:",
        zh: "试用到期：",
        ja: "トライアル終了：",
        ko: "체험 만료:",
        hi: "ट्रायल समाप्त:",
        es: "Prueba expira:",
        fr: "Essai expire le :",
        ar: "تنتهي التجربة:",
        bn: "ট্রায়াল শেষ:",
        pt: "Teste expira:",
        ru: "Пробный период истекает:",
        ur: "ٹرائل ختم ہوگا:",
        id: "Uji coba berakhir:",
        de: "Test endet am:",
        sw: "Jaribio linaisha:",
        mr: "ट्रायल संपते:",
      }),
      activeUntil: t({
        en: "Active until:",
        zh: "有效期至：",
        ja: "有効期限：",
        ko: "유효 기간:",
        hi: "तक सक्रिय:",
        es: "Activo hasta:",
        fr: "Actif jusqu'au :",
        ar: "نشط حتى:",
        bn: "সক্রিয় পর্যন্ত:",
        pt: "Ativo até:",
        ru: "Активен до:",
        ur: "تک فعال:",
        id: "Aktif hingga:",
        de: "Aktiv bis:",
        sw: "Inafanya kazi hadi:",
        mr: "पर्यंत सक्रिय:",
      }),
      trialExpired: t({
        en: "Your free trial has ended. You are on the Free plan.",
        zh: "您的免费试用已结束。您正在使用免费版。",
        ja: "無料トライアルが終了しました。現在フリープランです。",
        ko: "무료 체험이 종료되었습니다. 무료 플랜을 사용 중입니다.",
        hi: "आपका मुफ्त ट्रायल समाप्त हो गया है। आप निःशुल्क योजना पर हैं।",
        es: "Tu prueba gratuita ha terminado. Estás en el plan gratuito.",
        fr: "Votre essai gratuit est terminé. Vous êtes sur le plan gratuit.",
        ar: "انتهت تجربتك المجانية. أنت على الخطة المجانية.",
        bn: "আপনার বিনামূল্যে ট্রায়াল শেষ হয়েছে। আপনি বিনামূল্যে পরিকল্পনায় আছেন।",
        pt: "Seu teste gratuito terminou. Você está no plano gratuito.",
        ru: "Ваш бесплатный пробный период закончился. Вы на бесплатном плане.",
        ur: "آپ کا مفت ٹرائل ختم ہو گیا ہے۔ آپ مفت پلان پر ہیں۔",
        id: "Uji coba gratis Anda telah berakhir. Anda menggunakan paket Gratis.",
        de: "Ihre kostenlose Testversion ist abgelaufen. Sie nutzen den kostenlosen Plan.",
        sw: "Jaribio lako la bure limeisha. Uko kwenye mpango wa bure.",
        mr: "तुमचा विनामूल्य ट्रायल संपला आहे. तुम्ही विनामूल्य योजनेवर आहात.",
      }),
    },
    features: {
      free: {
        basicSpacedRepetition: t({
          en: "Basic spaced repetition",
          zh: "基础间隔重复",
          ja: "基本的な間隔反復",
          ko: "기본 간격 반복",
          hi: "बुनियादी स्पेस्ड रिपीटिशन",
          es: "Repetición espaciada básica",
          fr: "Répétition espacée de base",
          ar: "تكرار متباعد أساسي",
          bn: "মৌলিক স্পেসড রিপিটিশন",
          pt: "Repetição espaçada básica",
          ru: "Базовые интервальные повторения",
          ur: "بنیادی وقفے دار تکرار",
          id: "Pengulangan berjarak dasar",
          de: "Grundlegende verteilte Wiederholung",
          sw: "Marudio ya msingi yaliyopangwa",
          mr: "मूलभूत अंतराळ पुनरावृत्ती",
        }),
        unlimitedCards: t({
          en: "Unlimited flashcards",
          zh: "无限闪卡",
          ja: "無制限のフラッシュカード",
          ko: "무제한 플래시카드",
          hi: "असीमित फ्लैशकार्ड",
          es: "Tarjetas ilimitadas",
          fr: "Cartes illimitées",
          ar: "بطاقات تعليمية غير محدودة",
          bn: "সীমাহীন ফ্ল্যাশকার্ড",
          pt: "Flashcards ilimitados",
          ru: "Неограниченное количество карточек",
          ur: "لامحدود فلیش کارڈز",
          id: "Flashcard tak terbatas",
          de: "Unbegrenzte Karteikarten",
          sw: "Kadi za kumbukumbu zisizo na kikomo",
          mr: "अमर्यादित फ्लॅशकार्ड",
        }),
        videoSpeedControl: t({
          en: "Video speed control",
          zh: "视频速度控制",
          ja: "動画速度コントロール",
          ko: "비디오 속도 제어",
          hi: "वीडियो गति नियंत्रण",
          es: "Control de velocidad de video",
          fr: "Contrôle de vitesse vidéo",
          ar: "التحكم في سرعة الفيديو",
          bn: "ভিডিও গতি নিয়ন্ত্রণ",
          pt: "Controle de velocidade de vídeo",
          ru: "Управление скоростью видео",
          ur: "ویڈیو اسپیڈ کنٹرول",
          id: "Kontrol kecepatan video",
          de: "Video-Geschwindigkeitskontrolle",
          sw: "Udhibiti wa kasi ya video",
          mr: "व्हिडिओ स्पीड कंट्रोल",
        }),
        noPolyglot: t({
          en: "No Polyglot / AI features",
          zh: "无多语言/AI功能",
          ja: "Polyglot / AI機能なし",
          ko: "Polyglot / AI 기능 없음",
          hi: "कोई Polyglot / AI सुविधाएं नहीं",
          es: "Sin funciones Polyglot / IA",
          fr: "Pas de fonctionnalités Polyglot / IA",
          ar: "بدون ميزات Polyglot / AI",
          bn: "কোন Polyglot / AI বৈশিষ্ট্য নেই",
          pt: "Sem recursos Polyglot / IA",
          ru: "Нет функций Polyglot / AI",
          ur: "کوئی Polyglot / AI خصوصیات نہیں",
          id: "Tidak ada fitur Polyglot / AI",
          de: "Keine Polyglot / KI-Funktionen",
          sw: "Hakuna vipengele vya Polyglot / AI",
          mr: "Polyglot / AI वैशिष्ट्ये नाहीत",
        }),
      },
      pro: {
        allFreeFeatures: t({
          en: "All Free features",
          zh: "所有免费版功能",
          ja: "すべての無料機能",
          ko: "모든 무료 기능",
          hi: "सभी निःशुल्क सुविधाएं",
          es: "Todas las funciones gratuitas",
          fr: "Toutes les fonctionnalités gratuites",
          ar: "جميع الميزات المجانية",
          bn: "সমস্ত বিনামূল্যে বৈশিষ্ট্য",
          pt: "Todos os recursos gratuitos",
          ru: "Все бесплатные функции",
          ur: "تمام مفت خصوصیات",
          id: "Semua fitur Gratis",
          de: "Alle kostenlosen Funktionen",
          sw: "Vipengele vyote vya bure",
          mr: "सर्व विनामूल्य वैशिष्ट्ये",
        }),
        polyglotLearning: t({
          en: "Polyglot language learning",
          zh: "多语言学习",
          ja: "ポリグロット言語学習",
          ko: "폴리글랏 언어 학습",
          hi: "पॉलीग्लॉट भाषा सीखना",
          es: "Aprendizaje de idiomas Polyglot",
          fr: "Apprentissage des langues Polyglot",
          ar: "تعلم اللغات Polyglot",
          bn: "Polyglot ভাষা শিক্ষা",
          pt: "Aprendizado de idiomas Polyglot",
          ru: "Полиглот-изучение языков",
          ur: "Polyglot زبان سیکھنا",
          id: "Pembelajaran bahasa Polyglot",
          de: "Polyglot Sprachenlernen",
          sw: "Kujifunza lugha za Polyglot",
          mr: "Polyglot भाषा शिक्षण",
        }),
        aiTranslations: t({
          en: "AI-powered translations",
          zh: "AI翻译",
          ja: "AI翻訳",
          ko: "AI 번역",
          hi: "AI-संचालित अनुवाद",
          es: "Traducciones con IA",
          fr: "Traductions par IA",
          ar: "الترجمات بالذكاء الاصطناعي",
          bn: "AI-চালিত অনুবাদ",
          pt: "Traduções com IA",
          ru: "Переводы на основе ИИ",
          ur: "AI سے چلنے والے ترجمے",
          id: "Terjemahan bertenaga AI",
          de: "KI-gestützte Übersetzungen",
          sw: "Tafsiri zinazotumia AI",
          mr: "AI-चालित भाषांतरे",
        }),
        textToSpeech: t({
          en: "Text-to-speech",
          zh: "文字转语音",
          ja: "テキスト読み上げ",
          ko: "텍스트 음성 변환",
          hi: "टेक्स्ट-टू-स्पीच",
          es: "Texto a voz",
          fr: "Synthèse vocale",
          ar: "تحويل النص إلى كلام",
          bn: "টেক্সট-টু-স্পিচ",
          pt: "Texto para fala",
          ru: "Преобразование текста в речь",
          ur: "ٹیکسٹ ٹو اسپیچ",
          id: "Teks ke ucapan",
          de: "Text-zu-Sprache",
          sw: "Maandishi kuwa sauti",
          mr: "टेक्स्ट-टू-स्पीच",
        }),
        contactUs: t({
          en: "Contact us to upgrade",
          zh: "联系我们升级",
          ja: "アップグレードはお問い合わせください",
          ko: "업그레이드하려면 문의하세요",
          hi: "अपग्रेड के लिए संपर्क करें",
          es: "Contáctanos para mejorar",
          fr: "Contactez-nous pour passer à la version supérieure",
          ar: "تواصل معنا للترقية",
          bn: "আপগ্রেড করতে আমাদের সাথে যোগাযোগ করুন",
          pt: "Entre em contato para fazer upgrade",
          ru: "Свяжитесь с нами для обновления",
          ur: "اپ گریڈ کے لیے ہم سے رابطہ کریں",
          id: "Hubungi kami untuk meningkatkan",
          de: "Kontaktieren Sie uns für ein Upgrade",
          sw: "Wasiliana nasi ili kupandisha hadhi",
          mr: "अपग्रेड करण्यासाठी आमच्याशी संपर्क करा",
        }),
      },
    },
  },
} satisfies DeclarationContent;

export default membershipContent;
