import matter from "gray-matter";
import { marked } from "marked";
import corpus from "./blog.corpus.json";

/**
 * The markdown is bundled, not read from disk.
 *
 * This module used to do `fs.readFile(process.cwd()/blog/...)`, which works on
 * Vercel and returns nothing on Cloudflare Workers — silently, because the
 * reads were wrapped in `catch`, so the page rendered empty with a 200 instead
 * of failing. And there is no prerendered copy to fall back on: the root layout
 * awaits `headers()`/`cookies()`, which makes every route dynamically rendered,
 * so the blog is empty on the very first request rather than after some cache
 * window. Verified on a live Worker, where /en/blog served 0 posts.
 *
 * Bundling is therefore not an optimisation — it is the only way the content
 * reaches the Worker at all.
 *
 * Generated by scripts/gen-blog-corpus.ts (run from the pre-commit hook);
 * unit/blog-corpus.test.ts fails if it drifts from blog/.
 */
const POSTS: Record<string, string> = corpus;

// Map intlayer locale codes to blog directory names.
export function blogLocaleDir(locale: string): string {
  return locale;
}

export type PostMeta = {
  slug: string;
  title: string;
  date: string;
  summary: string;
  tags: string[];
};

export type Post = PostMeta & { contentHtml: string };

export async function getRawPost(locale: string, slug: string): Promise<string | null> {
  return POSTS[`${blogLocaleDir(locale)}/${slug}`] ?? null;
}

// Get raw post with English fallback (for blog index summaries)
export async function getRawPostWithFallback(locale: string, slug: string): Promise<string | null> {
  const localePost = await getRawPost(locale, slug);
  if (localePost) return localePost;

  // Fallback to English if locale version doesn't exist
  if (locale !== "en") {
    return await getRawPost("en", slug);
  }

  return null;
}

export function parsePost(raw: string, slug: string): Post {
  const { data, content } = matter(raw);
  return {
    slug,
    title: data.title ?? slug,
    date: data.date ?? "",
    summary: data.summary ?? "",
    tags: data.tags ?? [],
    contentHtml: marked(content) as string,
  };
}

export async function getPost(locale: string, slug: string): Promise<Post | null> {
  const raw = await getRawPost(locale, slug);
  return raw ? parsePost(raw, slug) : null;
}

export async function getAllSlugs(): Promise<string[]> {
  return Object.keys(POSTS)
    .filter((k) => k.startsWith("en/"))
    .map((k) => k.slice("en/".length))
    .sort()
    .reverse();
}
