// Generated by scripts/pre-commit.ts from public/lianki.user.js — do not edit by hand.
// Inlined rather than read from disk at runtime: the Workers runtime has no
// filesystem, so readFileSync(process.cwd()…) silently fell back to "0.0.0",
// which made the update prompt believe every install was already current.
export const LIANKI_USERSCRIPT_VERSION = "2.23.20";
