import { t, type DeclarationContent } from "intlayer";

const labImmersionPageContent = {
  key: "lab-immersion-page",
  content: {
    metadata: {
      title: t({
        en: "Immersion Web Matrix - Lianki Lab",
        zh: "沉浸式网站矩阵 - Lianki 实验室",
        ja: "イマージョン Web マトリックス - Lianki ラボ",
        ko: "몰입 웹 매트릭스 - Lianki 랩",
        fr: "Matrice web d'immersion - Lianki Labo",
        es: "Matriz web de inmersión - Lianki Laboratorio",
        de: "Immersions-Web-Matrix - Lianki Labor",
      }),
      description: t({
        en: "Desktop websites for language immersion in Chinese, Japanese, English, French, Korean, Spanish and German, organised by topic and register.",
        zh: "按主题和语域整理的中文、日语、英语、法语、韩语、西班牙语、德语沉浸式桌面网站。",
        ja: "中国語・日本語・英語・フランス語・韓国語・スペイン語・ドイツ語のイマージョン向けデスクトップサイトを、トピックと文体で整理。",
        ko: "중국어·일본어·영어·프랑스어·한국어·스페인어·독일어 몰입용 데스크톱 사이트를 주제와 문체별로 정리.",
        fr: "Sites web de bureau pour l'immersion en chinois, japonais, anglais, français, coréen, espagnol et allemand, classés par sujet et par registre.",
        es: "Sitios web de escritorio para la inmersión en chino, japonés, inglés, francés, coreano, español y alemán, organizados por tema y registro.",
        de: "Desktop-Websites für Sprachimmersion in Chinesisch, Japanisch, Englisch, Französisch, Koreanisch, Spanisch und Deutsch, nach Thema und Register geordnet.",
      }),
    },
    heading: t({
      en: "Immersion Web Matrix",
      zh: "沉浸式网站矩阵",
      ja: "イマージョン Web マトリックス",
      ko: "몰입 웹 매트릭스",
      fr: "Matrice web d'immersion",
      es: "Matriz web de inmersión",
      de: "Immersions-Web-Matrix",
    }),
    intro: t({
      en: "Strictly desktop websites — no app required — where native speakers write for each other. Pick the languages you are learning, open a site, and clip sentences into cards with the userscript as you read.",
      zh: "纯桌面网站，无需 App，母语者在这里写给彼此看。选好正在学的语言，打开一个网站，一边读一边用用户脚本把句子剪成卡片。",
      ja: "アプリ不要のデスクトップサイトだけ。ネイティブがネイティブに向けて書いている場所です。学習中の言語を選び、サイトを開き、読みながらユーザースクリプトで文をカードに切り出してください。",
      ko: "앱 없이 쓰는 데스크톱 사이트만 모았습니다. 원어민이 원어민에게 쓰는 곳이에요. 배우는 언어를 고르고 사이트를 열어, 읽으면서 유저스크립트로 문장을 카드로 만드세요.",
      fr: "Uniquement des sites web de bureau — sans application — où les natifs écrivent pour les natifs. Choisissez vos langues, ouvrez un site, et découpez des phrases en cartes avec le userscript pendant votre lecture.",
      es: "Solo sitios web de escritorio, sin app, donde los nativos escriben para nativos. Elige los idiomas que estudias, abre un sitio y recorta frases en tarjetas con el userscript mientras lees.",
      de: "Nur Desktop-Websites — keine App nötig —, auf denen Muttersprachler für Muttersprachler schreiben. Wähle deine Sprachen, öffne eine Seite und schneide beim Lesen mit dem Userscript Sätze in Karten.",
    }),
    languages: t({
      en: "Languages",
      zh: "语言",
      ja: "言語",
      ko: "언어",
      fr: "Langues",
      es: "Idiomas",
      de: "Sprachen",
    }),
    filterPlaceholder: t({
      en: "Filter topics or sites…",
      zh: "筛选主题或网站…",
      ja: "トピックやサイトを絞り込む…",
      ko: "주제나 사이트 검색…",
      fr: "Filtrer les sujets ou les sites…",
      es: "Filtrar temas o sitios…",
      de: "Themen oder Seiten filtern…",
    }),
    topic: t({
      en: "Topic",
      zh: "主题",
      ja: "トピック",
      ko: "주제",
      fr: "Sujet",
      es: "Tema",
      de: "Thema",
    }),
    noMatch: t({
      en: "Nothing matches that filter.",
      zh: "没有匹配的结果。",
      ja: "一致するものがありません。",
      ko: "일치하는 항목이 없습니다.",
      fr: "Rien ne correspond à ce filtre.",
      es: "Nada coincide con ese filtro.",
      de: "Nichts passt zu diesem Filter.",
    }),
    noLanguages: t({
      en: "Pick at least one language to see the matrix.",
      zh: "至少选择一种语言以显示矩阵。",
      ja: "マトリックスを表示するには言語を1つ以上選んでください。",
      ko: "매트릭스를 보려면 언어를 하나 이상 고르세요.",
      fr: "Choisissez au moins une langue pour voir la matrice.",
      es: "Elige al menos un idioma para ver la matriz.",
      de: "Wähle mindestens eine Sprache, um die Matrix zu sehen.",
    }),
    registers: {
      formal: t({
        en: "formal",
        zh: "正式",
        ja: "フォーマル",
        ko: "격식",
        fr: "soutenu",
        es: "formal",
        de: "formell",
      }),
      casual: t({
        en: "casual",
        zh: "日常",
        ja: "カジュアル",
        ko: "일상",
        fr: "courant",
        es: "coloquial",
        de: "locker",
      }),
      slang: t({
        en: "slang",
        zh: "网络用语",
        ja: "スラング",
        ko: "속어",
        fr: "argot",
        es: "jerga",
        de: "Slang",
      }),
      technical: t({
        en: "technical",
        zh: "技术",
        ja: "技術",
        ko: "기술",
        fr: "technique",
        es: "técnico",
        de: "fachlich",
      }),
      imperative: t({
        en: "imperative",
        zh: "祈使句",
        ja: "命令形",
        ko: "명령형",
        fr: "impératif",
        es: "imperativo",
        de: "Imperativ",
      }),
      spoken: t({
        en: "spoken",
        zh: "口语",
        ja: "話し言葉",
        ko: "구어",
        fr: "oral",
        es: "oral",
        de: "gesprochen",
      }),
    },
    howTo: {
      title: t({
        en: "How this fits Lianki",
        zh: "如何配合 Lianki 使用",
        ja: "Lianki との組み合わせ方",
        ko: "Lianki와 함께 쓰는 법",
        fr: "Comment ça s'articule avec Lianki",
        es: "Cómo encaja con Lianki",
        de: "Wie das zu Lianki passt",
      }),
      steps: {
        install: t({
          en: "Install the userscript",
          zh: "安装用户脚本",
          ja: "ユーザースクリプトを入れる",
          ko: "유저스크립트 설치",
          fr: "Installer le userscript",
          es: "Instalar el userscript",
          de: "Userscript installieren",
        }),
        installTail: t({
          en: " — it runs on every site in this table.",
          zh: "——它能在这张表里的每个网站上运行。",
          ja: " — この表のどのサイトでも動きます。",
          ko: " — 이 표의 모든 사이트에서 동작합니다.",
          fr: " — il fonctionne sur tous les sites de ce tableau.",
          es: ": funciona en todos los sitios de esta tabla.",
          de: " — es läuft auf jeder Seite in dieser Tabelle.",
        }),
        clip: t({
          en: "Read normally. When a sentence is worth keeping, select it and save it as a card — the page URL is remembered with it.",
          zh: "正常阅读。遇到值得记住的句子，选中并保存为卡片——页面网址会一并记录。",
          ja: "普通に読む。残したい文があれば選択してカードとして保存 — ページの URL も一緒に記録されます。",
          ko: "평소처럼 읽으세요. 남기고 싶은 문장이 있으면 선택해서 카드로 저장하세요. 페이지 URL도 함께 기억됩니다.",
          fr: "Lisez normalement. Quand une phrase vaut la peine, sélectionnez-la et enregistrez-la comme carte — l'URL de la page est mémorisée avec.",
          es: "Lee con normalidad. Cuando una frase merezca guardarse, selecciónala y guárdala como tarjeta; la URL de la página se recuerda con ella.",
          de: "Lies ganz normal. Wenn ein Satz es wert ist, markiere ihn und speichere ihn als Karte — die Seiten-URL wird mitgespeichert.",
        }),
        review: t({
          en: "Reviewing serves cards from the site you are currently on first, so you stay in one language and one register per session.",
          zh: "复习时会优先给出你当前所在网站的卡片，一次学习只停留在一种语言、一种语域。",
          ja: "復習では今いるサイトのカードを先に出すので、1 セッションを 1 言語・1 文体で通せます。",
          ko: "복습은 지금 있는 사이트의 카드를 먼저 보여주므로, 한 세션 동안 한 언어·한 문체에 머물 수 있습니다.",
          fr: "La révision sert d'abord les cartes du site où vous êtes, pour rester sur une langue et un registre par session.",
          es: "El repaso muestra primero las tarjetas del sitio en el que estás, así te quedas en un idioma y un registro por sesión.",
          de: "Die Wiederholung zeigt zuerst Karten von der Seite, auf der du gerade bist — so bleibst du pro Sitzung bei einer Sprache und einem Register.",
        }),
      },
    },
  },
} satisfies DeclarationContent;

export default labImmersionPageContent;
