import { t, type DeclarationContent } from "intlayer";

const polyglotPageContent = {
  key: "polyglot-page",
  content: {
    metadata: {
      title: t({
        en: "Polyglot Matrix - Lianki",
        zh: "多语言矩阵 - Lianki",
        ja: "ポリグロットマトリックス - Lianki",
        ko: "폴리글롯 매트릭스 - Lianki",
        hi: "पॉलीग्लॉट मैट्रिक्स - Lianki",
        es: "Matriz Políglota - Lianki",
        fr: "Matrice Polyglotte - Lianki",
        ar: "مصفوفة متعددة اللغات - Lianki",
        bn: "পলিগ্লট ম্যাট্রিক্স - Lianki",
        pt: "Matriz Poliglota - Lianki",
        ru: "Полиглот Матрица - Lianki",
        ur: "پولی گلوٹ میٹرکس - Lianki",
        id: "Matriks Poliglot - Lianki",
        de: "Polyglott-Matrix - Lianki",
        sw: "Matriki ya Lugha Nyingi - Lianki",
        mr: "पॉलीग्लॉट मॅट्रिक्स - Lianki",
      }),
      description: t({
        en: "Learn to answer common questions in multiple languages simultaneously",
        zh: "同时学习用多种语言回答常见问题",
        ja: "複数の言語で一般的な質問に答えることを学ぶ",
        ko: "여러 언어로 일반적인 질문에 답하는 법을 동시에 학습하세요",
        hi: "एक साथ कई भाषाओं में सामान्य प्रश्नों का उत्तर देना सीखें",
        es: "Aprende a responder preguntas comunes en múltiples idiomas simultáneamente",
        fr: "Apprenez à répondre aux questions courantes dans plusieurs langues simultanément",
        ar: "تعلم الإجابة على الأسئلة الشائعة بلغات متعددة في وقت واحد",
        bn: "একসাথে একাধিক ভাষায় সাধারণ প্রশ্নের উত্তর দিতে শিখুন",
        pt: "Aprenda a responder perguntas comuns em vários idiomas simultaneamente",
        ru: "Научитесь отвечать на общие вопросы на нескольких языках одновременно",
        ur: "بیک وقت متعدد زبانوں میں عام سوالات کے جوابات دینا سیکھیں",
        id: "Pelajari cara menjawab pertanyaan umum dalam beberapa bahasa secara bersamaan",
        de: "Lernen Sie, häufige Fragen gleichzeitig in mehreren Sprachen zu beantworten",
        sw: "Jifunze kujibu maswali ya kawaida katika lugha nyingi kwa wakati mmoja",
        mr: "एकाच वेळी अनेक भाषांमध्ये सामान्य प्रश्नांची उत्तरे देणे शिका",
      }),
    },
    heading: t({
      en: "Polyglot Matrix",
      zh: "多语言矩阵",
      ja: "ポリグロットマトリックス",
      ko: "폴리글롯 매트릭스",
      hi: "पॉलीग्लॉट मैट्रिक्स",
      es: "Matriz Políglota",
      fr: "Matrice Polyglotte",
      ar: "مصفوفة متعددة اللغات",
      bn: "পলিগ্লট ম্যাট্রিক্স",
      pt: "Matriz Poliglota",
      ru: "Полиглот Матрица",
      ur: "پولی گلوٹ میٹرکس",
      id: "Matriks Poliglot",
      de: "Polyglott-Matrix",
      sw: "Matriki ya Lugha Nyingi",
      mr: "पॉलीग्लॉट मॅट्रिक्स",
    }),
    description: t({
      en: "Learn to answer common questions in multiple languages simultaneously",
      zh: "同时学习用多种语言回答常见问题",
      ja: "複数の言語で一般的な質問に答えることを学ぶ",
      ko: "여러 언어로 일반적인 질문에 답하는 법을 동시에 학습하세요",
      hi: "एक साथ कई भाषाओं में सामान्य प्रश्नों का उत्तर देना सीखें",
      es: "Aprende a responder preguntas comunes en múltiples idiomas simultáneamente",
      fr: "Apprenez à répondre aux questions courantes dans plusieurs langues simultanément",
      ar: "تعلم الإجابة على الأسئلة الشائعة بلغات متعددة في وقت واحد",
      bn: "একসাথে একাধিক ভাষায় সাধারণ প্রশ্নের উত্তর দিতে শিখুন",
      pt: "Aprenda a responder perguntas comuns em vários idiomas simultaneamente",
      ru: "Научитесь отвечать на общие вопросы на нескольких языках одновременно",
      ur: "بیک وقت متعدد زبانوں میں عام سوالات کے جوابات دینا سیکھیں",
      id: "Pelajari cara menjawab pertanyaan umum dalam beberapa bahasa secara bersamaan",
      de: "Lernen Sie, häufige Fragen gleichzeitig in mehreren Sprachen zu beantworten",
      sw: "Jifunze kujibu maswali ya kawaida katika lugha nyingi kwa wakati mmoja",
      mr: "एकाच वेळी अनेक भाषांमध्ये सामान्य प्रश्नांची उत्तरे देणे शिका",
    }),
    selectMotherTongue: t({
      en: "Select Your Mother Tongue",
      zh: "选择您的母语",
      ja: "母国語を選択",
      ko: "모국어 선택",
      hi: "अपनी मातृभाषा चुनें",
      es: "Seleccione su Lengua Materna",
      fr: "Sélectionnez votre Langue Maternelle",
      ar: "حدد لغتك الأم",
      bn: "আপনার মাতৃভাষা নির্বাচন করুন",
      pt: "Selecione sua Língua Materna",
      ru: "Выберите ваш Родной Язык",
      ur: "اپنی مادری زبان منتخب کریں",
      id: "Pilih Bahasa Ibu Anda",
      de: "Wählen Sie Ihre Muttersprache",
      sw: "Chagua Lugha Yako ya Mama",
      mr: "तुमची मातृभाषा निवडा",
    }),
    selectTargetLanguages: t({
      en: "Select Target Languages (1 or more)",
      zh: "选择目标语言（1 种或更多）",
      ja: "対象言語を選択（1つ以上）",
      ko: "대상 언어 선택 (1개 이상)",
      hi: "लक्ष्य भाषाएँ चुनें (1 या अधिक)",
      es: "Seleccione Idiomas Objetivo (1 o más)",
      fr: "Sélectionnez les Langues Cibles (1 ou plus)",
      ar: "حدد اللغات المستهدفة (واحدة أو أكثر)",
      bn: "লক্ষ্য ভাষা নির্বাচন করুন (১ বা তার বেশি)",
      pt: "Selecione Idiomas Alvo (1 ou mais)",
      ru: "Выберите Целевые Языки (1 или более)",
      ur: "ہدف زبانیں منتخب کریں (1 یا زیادہ)",
      id: "Pilih Bahasa Target (1 atau lebih)",
      de: "Wählen Sie Zielsprachen (1 oder mehr)",
      sw: "Chagua Lugha Lengwa (1 au zaidi)",
      mr: "लक्ष्य भाषा निवडा (1 किंवा अधिक)",
    }),
    continueToQuestions: t({
      en: "Continue to Questions ({count} languages selected)",
      zh: "继续到问题（已选择 {count} 种语言）",
      ja: "質問に進む（{count} 言語選択済み）",
      ko: "질문으로 계속 ({count}개 언어 선택됨)",
      hi: "प्रश्नों पर जारी रखें ({count} भाषाएँ चयनित)",
      es: "Continuar a las Preguntas ({count} idiomas seleccionados)",
      fr: "Continuer vers les Questions ({count} langues sélectionnées)",
      ar: "المتابعة إلى الأسئلة ({count} لغات محددة)",
      bn: "প্রশ্নগুলিতে চালিয়ে যান ({count} ভাষা নির্বাচিত)",
      pt: "Continuar para as Perguntas ({count} idiomas selecionados)",
      ru: "Продолжить к Вопросам ({count} языков выбрано)",
      ur: "سوالات پر جاری رکھیں ({count} زبانیں منتخب)",
      id: "Lanjutkan ke Pertanyaan ({count} bahasa dipilih)",
      de: "Zu den Fragen ({count} Sprachen ausgewählt)",
      sw: "Endelea kwa Maswali (lugha {count} zimechaguliwa)",
      mr: "प्रश्नांवर सुरू ठेवा ({count} भाषा निवडल्या)",
    }),
    motherTongueLabel: t({
      en: "Mother tongue: {lang} → Learning: {langs}",
      zh: "母语：{lang} → 学习：{langs}",
      ja: "母国語：{lang} → 学習中：{langs}",
      ko: "모국어: {lang} → 학습 중: {langs}",
      hi: "मातृभाषा: {lang} → सीखना: {langs}",
      es: "Lengua materna: {lang} → Aprendiendo: {langs}",
      fr: "Langue maternelle: {lang} → Apprentissage: {langs}",
      ar: "اللغة الأم: {lang} ← التعلم: {langs}",
      bn: "মাতৃভাষা: {lang} → শিখছি: {langs}",
      pt: "Língua materna: {lang} → Aprendendo: {langs}",
      ru: "Родной язык: {lang} → Изучаю: {langs}",
      ur: "مادری زبان: {lang} → سیکھ رہے ہیں: {langs}",
      id: "Bahasa ibu: {lang} → Belajar: {langs}",
      de: "Muttersprache: {lang} → Lerne: {langs}",
      sw: "Lugha ya mama: {lang} → Kujifunza: {langs}",
      mr: "मातृभाषा: {lang} → शिकत आहे: {langs}",
    }),
    generateAll: t({
      en: "Generate All",
      zh: "全部生成",
      ja: "すべて生成",
      ko: "모두 생성",
      hi: "सभी उत्पन्न करें",
      es: "Generar Todo",
      fr: "Tout Générer",
      ar: "إنشاء الكل",
      bn: "সবকিছু তৈরি করুন",
      pt: "Gerar Tudo",
      ru: "Сгенерировать Всё",
      ur: "سب بنائیں",
      id: "Buat Semua",
      de: "Alles Generieren",
      sw: "Tengeneza Zote",
      mr: "सर्व तयार करा",
    }),
    changeLanguages: t({
      en: "Change Languages",
      zh: "更改语言",
      ja: "言語を変更",
      ko: "언어 변경",
      hi: "भाषाएँ बदलें",
      es: "Cambiar Idiomas",
      fr: "Changer de Langues",
      ar: "تغيير اللغات",
      bn: "ভাষা পরিবর্তন করুন",
      pt: "Alterar Idiomas",
      ru: "Изменить Языки",
      ur: "زبانیں تبدیل کریں",
      id: "Ubah Bahasa",
      de: "Sprachen Ändern",
      sw: "Badilisha Lugha",
      mr: "भाषा बदला",
    }),
    addQuestionPlaceholder: t({
      en: "Add your own question...",
      zh: "添加您自己的问题...",
      ja: "質問を追加...",
      ko: "질문 추가...",
      hi: "अपना प्रश्न जोड़ें...",
      es: "Agregue su propia pregunta...",
      fr: "Ajoutez votre propre question...",
      ar: "أضف سؤالك الخاص...",
      bn: "আপনার নিজের প্রশ্ন যোগ করুন...",
      pt: "Adicione sua própria pergunta...",
      ru: "Добавьте свой вопрос...",
      ur: "اپنا سوال شامل کریں...",
      id: "Tambahkan pertanyaan Anda sendiri...",
      de: "Fügen Sie Ihre eigene Frage hinzu...",
      sw: "Ongeza swali lako mwenyewe...",
      mr: "तुमचा स्वतःचा प्रश्न जोडा...",
    }),
    addQuestion: t({
      en: "Add Question",
      zh: "添加问题",
      ja: "質問を追加",
      ko: "질문 추가",
      hi: "प्रश्न जोड़ें",
      es: "Agregar Pregunta",
      fr: "Ajouter une Question",
      ar: "إضافة سؤال",
      bn: "প্রশ্ন যোগ করুন",
      pt: "Adicionar Pergunta",
      ru: "Добавить Вопрос",
      ur: "سوال شامل کریں",
      id: "Tambah Pertanyaan",
      de: "Frage Hinzufügen",
      sw: "Ongeza Swali",
      mr: "प्रश्न जोडा",
    }),
    questionYourAnswer: t({
      en: "Question / Your Answer",
      zh: "问题 / 您的回答",
      ja: "質問 / あなたの回答",
      ko: "질문 / 당신의 답변",
      hi: "प्रश्न / आपका उत्तर",
      es: "Pregunta / Su Respuesta",
      fr: "Question / Votre Réponse",
      ar: "السؤال / إجابتك",
      bn: "প্রশ্ন / আপনার উত্তর",
      pt: "Pergunta / Sua Resposta",
      ru: "Вопрос / Ваш Ответ",
      ur: "سوال / آپ کا جواب",
      id: "Pertanyaan / Jawaban Anda",
      de: "Frage / Ihre Antwort",
      sw: "Swali / Jibu Lako",
      mr: "प्रश्न / तुमचे उत्तर",
    }),
    answerInLanguage: t({
      en: "Answer in {lang}...",
      zh: "用 {lang} 回答...",
      ja: "{lang} で回答...",
      ko: "{lang}로 답변...",
      hi: "{lang} में उत्तर दें...",
      es: "Responda en {lang}...",
      fr: "Répondez en {lang}...",
      ar: "أجب بـ {lang}...",
      bn: "{lang} এ উত্তর দিন...",
      pt: "Responda em {lang}...",
      ru: "Ответьте на {lang}...",
      ur: "{lang} میں جواب دیں...",
      id: "Jawab dalam {lang}...",
      de: "Antworten Sie auf {lang}...",
      sw: "Jibu kwa {lang}...",
      mr: "{lang} मध्ये उत्तर द्या...",
    }),
    generating: t({
      en: "Generating...",
      zh: "生成中...",
      ja: "生成中...",
      ko: "생성 중...",
      hi: "उत्पन्न हो रहा है...",
      es: "Generando...",
      fr: "Génération...",
      ar: "جاري الإنشاء...",
      bn: "তৈরি হচ্ছে...",
      pt: "Gerando...",
      ru: "Генерация...",
      ur: "بنایا جا رہا ہے...",
      id: "Membuat...",
      de: "Generiere...",
      sw: "Inatengeneza...",
      mr: "तयार करत आहे...",
    }),
    generateRow: t({
      en: "Generate Row",
      zh: "生成行",
      ja: "行を生成",
      ko: "행 생성",
      hi: "पंक्ति उत्पन्न करें",
      es: "Generar Fila",
      fr: "Générer la Ligne",
      ar: "إنشاء الصف",
      bn: "সারি তৈরি করুন",
      pt: "Gerar Linha",
      ru: "Сгенерировать Строку",
      ur: "قطار بنائیں",
      id: "Buat Baris",
      de: "Zeile Generieren",
      sw: "Tengeneza Mstari",
      mr: "पंक्ती तयार करा",
    }),
    questionLabel: t({
      en: "Q:",
      zh: "问：",
      ja: "Q:",
      ko: "Q:",
      hi: "प्र:",
      es: "P:",
      fr: "Q:",
      ar: "س:",
      bn: "প্রঃ",
      pt: "P:",
      ru: "В:",
      ur: "س:",
      id: "T:",
      de: "F:",
      sw: "S:",
      mr: "प्र:",
    }),
    answerLabel: t({
      en: "A:",
      zh: "答：",
      ja: "A:",
      ko: "A:",
      hi: "उ:",
      es: "R:",
      fr: "R:",
      ar: "ج:",
      bn: "উঃ",
      pt: "R:",
      ru: "О:",
      ur: "ج:",
      id: "J:",
      de: "A:",
      sw: "J:",
      mr: "उ:",
    }),
    playQuestion: t({
      en: "▶ Q",
      zh: "▶ 问",
      ja: "▶ Q",
      ko: "▶ Q",
      hi: "▶ प्र",
      es: "▶ P",
      fr: "▶ Q",
      ar: "▶ س",
      bn: "▶ প্রঃ",
      pt: "▶ P",
      ru: "▶ В",
      ur: "▶ س",
      id: "▶ T",
      de: "▶ F",
      sw: "▶ S",
      mr: "▶ प्र",
    }),
    playAnswer: t({
      en: "▶ A",
      zh: "▶ 答",
      ja: "▶ A",
      ko: "▶ A",
      hi: "▶ उ",
      es: "▶ R",
      fr: "▶ R",
      ar: "▶ ج",
      bn: "▶ উঃ",
      pt: "▶ R",
      ru: "▶ О",
      ur: "▶ ج",
      id: "▶ J",
      de: "▶ A",
      sw: "▶ J",
      mr: "▶ उ",
    }),
    regenerate: t({
      en: "Regenerate",
      zh: "重新生成",
      ja: "再生成",
      ko: "재생성",
      hi: "पुन: उत्पन्न करें",
      es: "Regenerar",
      fr: "Régénérer",
      ar: "إعادة الإنشاء",
      bn: "পুনরায় তৈরি করুন",
      pt: "Regerar",
      ru: "Перегенерировать",
      ur: "دوبارہ بنائیں",
      id: "Buat Ulang",
      de: "Neu Generieren",
      sw: "Tengeneza Tena",
      mr: "पुन्हा तयार करा",
    }),
    generate: t({
      en: "Generate",
      zh: "生成",
      ja: "生成",
      ko: "생성",
      hi: "उत्पन्न करें",
      es: "Generar",
      fr: "Générer",
      ar: "إنشاء",
      bn: "তৈরি করুন",
      pt: "Gerar",
      ru: "Сгенерировать",
      ur: "بنائیں",
      id: "Buat",
      de: "Generieren",
      sw: "Tengeneza",
      mr: "तयार करा",
    }),
    answerFirst: t({
      en: "Answer first",
      zh: "先回答",
      ja: "まず回答",
      ko: "먼저 답변",
      hi: "पहले उत्तर दें",
      es: "Responda primero",
      fr: "Répondez d'abord",
      ar: "أجب أولاً",
      bn: "প্রথমে উত্তর দিন",
      pt: "Responda primeiro",
      ru: "Сначала ответьте",
      ur: "پہلے جواب دیں",
      id: "Jawab dulu",
      de: "Zuerst antworten",
      sw: "Jibu kwanza",
      mr: "प्रथम उत्तर द्या",
    }),
    cellsGenerated: t({
      en: "{count} cells generated",
      zh: "已生成 {count} 个单元格",
      ja: "{count} セル生成済み",
      ko: "{count}개 셀 생성됨",
      hi: "{count} सेल उत्पन्न",
      es: "{count} celdas generadas",
      fr: "{count} cellules générées",
      ar: "{count} خلية تم إنشاؤها",
      bn: "{count} সেল তৈরি হয়েছে",
      pt: "{count} células geradas",
      ru: "{count} ячеек сгенерировано",
      ur: "{count} خلیے بنائے گئے",
      id: "{count} sel dibuat",
      de: "{count} Zellen generiert",
      sw: "Seli {count} zimetengenezwa",
      mr: "{count} सेल तयार केले",
    }),
    saving: t({
      en: "Saving...",
      zh: "保存中...",
      ja: "保存中...",
      ko: "저장 중...",
      hi: "सहेज रहे हैं...",
      es: "Guardando...",
      fr: "Enregistrement...",
      ar: "جاري الحفظ...",
      bn: "সংরক্ষণ হচ্ছে...",
      pt: "Salvando...",
      ru: "Сохранение...",
      ur: "محفوظ ہو رہا ہے...",
      id: "Menyimpan...",
      de: "Speichern...",
      sw: "Inakohoa...",
      mr: "सेव्ह करत आहे...",
    }),
    saveToCards: t({
      en: "Save to Lianki Cards",
      zh: "保存到 Lianki 卡片",
      ja: "Lianki カードに保存",
      ko: "Lianki 카드에 저장",
      hi: "Lianki कार्ड में सहेजें",
      es: "Guardar en Tarjetas de Lianki",
      fr: "Enregistrer dans les Cartes Lianki",
      ar: "حفظ في بطاقات Lianki",
      bn: "Lianki কার্ডে সংরক্ষণ করুন",
      pt: "Salvar nos Cartões Lianki",
      ru: "Сохранить в Карточки Lianki",
      ur: "Lianki کارڈز میں محفوظ کریں",
      id: "Simpan ke Kartu Lianki",
      de: "Zu Lianki-Karten Speichern",
      sw: "Hifadhi kwenye Kadi za Lianki",
      mr: "Lianki कार्ड्समध्ये सेव्ह करा",
    }),
    errors: {
      failedToGenerate: t({
        en: "Failed to generate translation. Please try again.",
        zh: "生成翻译失败。请重试。",
        ja: "翻訳の生成に失敗しました。もう一度お試しください。",
        ko: "번역 생성 실패. 다시 시도해 주세요.",
        hi: "अनुवाद उत्पन्न करने में विफल। कृपया पुनः प्रयास करें।",
        es: "Error al generar la traducción. Por favor, inténtelo de nuevo.",
        fr: "Échec de la génération de la traduction. Veuillez réessayer.",
        ar: "فشل إنشاء الترجمة. يرجى المحاولة مرة أخرى.",
        bn: "অনুবাদ তৈরি করতে ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।",
        pt: "Falha ao gerar tradução. Por favor, tente novamente.",
        ru: "Не удалось сгенерировать перевод. Пожалуйста, попробуйте снова.",
        ur: "ترجمہ بنانے میں ناکام۔ براہ کرم دوبارہ کوشش کریں۔",
        id: "Gagal membuat terjemahan. Silakan coba lagi.",
        de: "Fehler beim Generieren der Übersetzung. Bitte versuchen Sie es erneut.",
        sw: "Imeshindwa kutengeneza tafsiri. Tafadhali jaribu tena.",
        mr: "भाषांतर तयार करण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
      }),
      failedToGenerateRow: t({
        en: "Failed to generate row. Please try again.",
        zh: "生成行失败。请重试。",
        ja: "行の生成に失敗しました。もう一度お試しください。",
        ko: "행 생성 실패. 다시 시도해 주세요.",
        hi: "पंक्ति उत्पन्न करने में विफल। कृपया पुनः प्रयास करें।",
        es: "Error al generar la fila. Por favor, inténtelo de nuevo.",
        fr: "Échec de la génération de la ligne. Veuillez réessayer.",
        ar: "فشل إنشاء الصف. يرجى المحاولة مرة أخرى.",
        bn: "সারি তৈরি করতে ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।",
        pt: "Falha ao gerar linha. Por favor, tente novamente.",
        ru: "Не удалось сгенерировать строку. Пожалуйста, попробуйте снова.",
        ur: "قطار بنانے میں ناکام۔ براہ کرم دوبارہ کوشش کریں۔",
        id: "Gagal membuat baris. Silakan coba lagi.",
        de: "Fehler beim Generieren der Zeile. Bitte versuchen Sie es erneut.",
        sw: "Imeshindwa kutengeneza mstari. Tafadhali jaribu tena.",
        mr: "पंक्ती तयार करण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
      }),
      signInRequired: t({
        en: "Please sign in to save cards",
        zh: "请登录以保存卡片",
        ja: "カードを保存するにはサインインしてください",
        ko: "카드를 저장하려면 로그인하세요",
        hi: "कार्ड सहेजने के लिए कृपया साइन इन करें",
        es: "Por favor, inicie sesión para guardar las tarjetas",
        fr: "Veuillez vous connecter pour enregistrer les cartes",
        ar: "يرجى تسجيل الدخول لحفظ البطاقات",
        bn: "কার্ড সংরক্ষণ করতে অনুগ্রহ করে সাইন ইন করুন",
        pt: "Por favor, faça login para salvar os cartões",
        ru: "Пожалуйста, войдите, чтобы сохранить карточки",
        ur: "کارڈز محفوظ کرنے کے لیے براہ کرم سائن ان کریں",
        id: "Silakan masuk untuk menyimpan kartu",
        de: "Bitte melden Sie sich an, um Karten zu speichern",
        sw: "Tafadhali ingia ili kuhifadhi kadi",
        mr: "कार्ड सेव्ह करण्यासाठी कृपया साइन इन करा",
      }),
      failedToSave: t({
        en: "Failed to save cards. Please try again.",
        zh: "保存卡片失败。请重试。",
        ja: "カードの保存に失敗しました。もう一度お試しください。",
        ko: "카드 저장 실패. 다시 시도해 주세요.",
        hi: "कार्ड सहेजने में विफल। कृपया पुनः प्रयास करें।",
        es: "Error al guardar las tarjetas. Por favor, inténtelo de nuevo.",
        fr: "Échec de l'enregistrement des cartes. Veuillez réessayer.",
        ar: "فشل حفظ البطاقات. يرجى المحاولة مرة أخرى.",
        bn: "কার্ড সংরক্ষণ করতে ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।",
        pt: "Falha ao salvar cartões. Por favor, tente novamente.",
        ru: "Не удалось сохранить карточки. Пожалуйста, попробуйте снова.",
        ur: "کارڈز محفوظ کرنے میں ناکام۔ براہ کرم دوبارہ کوشش کریں۔",
        id: "Gagal menyimpan kartu. Silakan coba lagi.",
        de: "Fehler beim Speichern der Karten. Bitte versuchen Sie es erneut.",
        sw: "Imeshindwa kuhifadhi kadi. Tafadhali jaribu tena.",
        mr: "कार्ड सेव्ह करण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
      }),
    },
    categories: {
      basicIntroduction: t({
        en: "Basic Introduction",
        zh: "基本介绍",
        ja: "基本紹介",
        ko: "기본 소개",
        hi: "बुनियादी परिचय",
        es: "Introducción Básica",
        fr: "Introduction de Base",
        ar: "المقدمة الأساسية",
        bn: "মৌলিক পরিচয়",
        pt: "Introdução Básica",
        ru: "Базовое Представление",
        ur: "بنیادی تعارف",
        id: "Perkenalan Dasar",
        de: "Grundlegende Einführung",
        sw: "Utangulizi wa Msingi",
        mr: "मूलभूत ओळख",
      }),
      dailyLife: t({
        en: "Daily Life",
        zh: "日常生活",
        ja: "日常生活",
        ko: "일상 생활",
        hi: "दैनिक जीवन",
        es: "Vida Diaria",
        fr: "Vie Quotidienne",
        ar: "الحياة اليومية",
        bn: "দৈনন্দিন জীবন",
        pt: "Vida Diária",
        ru: "Повседневная Жизнь",
        ur: "روزمرہ زندگی",
        id: "Kehidupan Sehari-hari",
        de: "Alltag",
        sw: "Maisha ya Kila Siku",
        mr: "दैनंदिन जीवन",
      }),
      familyRelationships: t({
        en: "Family & Relationships",
        zh: "家庭与关系",
        ja: "家族と人間関係",
        ko: "가족 및 관계",
        hi: "परिवार और रिश्ते",
        es: "Familia y Relaciones",
        fr: "Famille et Relations",
        ar: "العائلة والعلاقات",
        bn: "পরিবার এবং সম্পর্ক",
        pt: "Família e Relacionamentos",
        ru: "Семья и Отношения",
        ur: "خاندان اور تعلقات",
        id: "Keluarga & Hubungan",
        de: "Familie & Beziehungen",
        sw: "Familia na Uhusiano",
        mr: "कुटुंब आणि नातेसंबंध",
      }),
      interestsPreferences: t({
        en: "Interests & Preferences",
        zh: "兴趣与偏好",
        ja: "興味と好み",
        ko: "관심사 및 선호도",
        hi: "रुचियाँ और प्राथमिकताएँ",
        es: "Intereses y Preferencias",
        fr: "Intérêts et Préférences",
        ar: "الاهتمامات والتفضيلات",
        bn: "আগ্রহ এবং পছন্দসমূহ",
        pt: "Interesses e Preferências",
        ru: "Интересы и Предпочтения",
        ur: "دلچسپیاں اور ترجیحات",
        id: "Minat & Preferensi",
        de: "Interessen & Vorlieben",
        sw: "Maslahi na Mapendeleo",
        mr: "आवडी आणि प्राधान्ये",
      }),
      languageLearning: t({
        en: "Language Learning",
        zh: "语言学习",
        ja: "言語学習",
        ko: "언어 학습",
        hi: "भाषा सीखना",
        es: "Aprendizaje de Idiomas",
        fr: "Apprentissage des Langues",
        ar: "تعلم اللغات",
        bn: "ভাষা শিক্ষা",
        pt: "Aprendizado de Idiomas",
        ru: "Изучение Языков",
        ur: "زبان سیکھنا",
        id: "Pembelajaran Bahasa",
        de: "Sprachenlernen",
        sw: "Kujifunza Lugha",
        mr: "भाषा शिकणे",
      }),
      futureGoals: t({
        en: "Future & Goals",
        zh: "未来与目标",
        ja: "未来と目標",
        ko: "미래 및 목표",
        hi: "भविष्य और लक्ष्य",
        es: "Futuro y Objetivos",
        fr: "Futur et Objectifs",
        ar: "المستقبل والأهداف",
        bn: "ভবিষ্যত এবং লক্ষ্য",
        pt: "Futuro e Objetivos",
        ru: "Будущее и Цели",
        ur: "مستقبل اور مقاصد",
        id: "Masa Depan & Tujuan",
        de: "Zukunft & Ziele",
        sw: "Siku Zijazo na Malengo",
        mr: "भविष्य आणि उद्दिष्टे",
      }),
      custom: t({
        en: "Custom",
        zh: "自定义",
        ja: "カスタム",
        ko: "사용자 지정",
        hi: "कस्टम",
        es: "Personalizado",
        fr: "Personnalisé",
        ar: "مخصص",
        bn: "কাস্টম",
        pt: "Personalizado",
        ru: "Пользовательские",
        ur: "اپنی مرضی کا",
        id: "Kustom",
        de: "Benutzerdefiniert",
        sw: "Maalum",
        mr: "सानुकूल",
      }),
    },
  },
} satisfies DeclarationContent;

export default polyglotPageContent;
