import { t, type DeclarationContent } from "intlayer";

const addNotePageContent = {
  key: "add-note-page",
  content: {
    metadata: {
      title: t({
        en: "Add Note - Lianki",
        zh: "添加笔记 - Lianki",
        ja: "ノートを追加 - Lianki",
        ko: "노트 추가 - Lianki",
        hi: "नोट जोड़ें - Lianki",
        es: "Añadir Nota - Lianki",
        fr: "Ajouter une Note - Lianki",
        ar: "إضافة ملاحظة - Lianki",
        bn: "নোট যোগ করুন - Lianki",
        pt: "Adicionar Nota - Lianki",
        ru: "Добавить Заметку - Lianki",
        ur: "نوٹ شامل کریں - Lianki",
        id: "Tambah Catatan - Lianki",
        de: "Notiz Hinzufügen - Lianki",
        sw: "Ongeza Kumbukumbu - Lianki",
        mr: "नोट जोडा - Lianki",
      }),
      description: t({
        en: "Add a new URL to your learning queue",
        zh: "将新 URL 添加到您的学习队列",
        ja: "学習キューに新しい URL を追加",
        ko: "학습 큐에 새 URL 추가",
        hi: "अपनी सीखने की कतार में एक नया URL जोड़ें",
        es: "Añadir una nueva URL a tu cola de aprendizaje",
        fr: "Ajouter une nouvelle URL à votre file d'apprentissage",
        ar: "أضف عنوان URL جديد إلى قائمة التعلم الخاصة بك",
        bn: "আপনার শেখার সারিতে একটি নতুন URL যোগ করুন",
        pt: "Adicionar um novo URL à sua fila de aprendizado",
        ru: "Добавить новый URL в вашу очередь обучения",
        ur: "اپنی سیکھنے کی قطار میں نیا URL شامل کریں",
        id: "Tambahkan URL baru ke antrean belajar Anda",
        de: "Fügen Sie eine neue URL zu Ihrer Lernwarteschlange hinzu",
        sw: "Ongeza URL mpya kwenye foleni yako ya kujifunza",
        mr: "आपल्या शिकण्याच्या रांगेत नवीन URL जोडा",
      }),
    },
    adding: t({
      en: "Adding...",
      zh: "添加中...",
      ja: "追加中...",
      ko: "추가 중...",
      hi: "जोड़ा जा रहा है...",
      es: "Añadiendo...",
      fr: "Ajout en cours...",
      ar: "جاري الإضافة...",
      bn: "যোগ করা হচ্ছে...",
      pt: "Adicionando...",
      ru: "Добавление...",
      ur: "شامل ہو رہا ہے...",
      id: "Menambahkan...",
      de: "Wird hinzugefügt...",
      sw: "Inaongeza...",
      mr: "जोडत आहे...",
    }),
  },
} satisfies DeclarationContent;

export default addNotePageContent;
